### ISSUE TITLE
Importing private key fails after all "bad self certificates" removed

### ISSUE THREAD

**Issue by ikelos** [open-keychain/open-keychain#1003]
Hi there,

I recently tried to import my desktop gpg keys into openkeychain.  The error log is quite useful, but unfortunately does not give me much to go on (and nor does the source code).  I exported my key from gpg2 using 'gpg2 --export-secret-key -a "name" > file.asc'.  After transfering the asc file over, I attempted to import it.  The failure message gave me the following:

[Purple] Importing secret key 0xfffffffffffff
[Purple] Canonicalizing secret key 0xffffffffffffff
Processing master key
[Yellow] Removing bad self certificate for user ID 'First user'
Removing invalid user ID 'First user'
[Yellow] Removing bad self certificate for user ID 'Second user'
Removing invalid user ID 'Second user'
[Red] Keyring has no valid user IDs!
Merging in self-certificates data from public keyring
[Green] Nothing to merge
[Purple] Canonicalizing secret key 0xfffffffffffff
A which point it repeats down to the red again...

I've tried it without the public keys installed before hand, with the public keys installed, with the public keys installed and certified by another cert on the phone, with the public keys imported at the same time, all of which gave me the same pattern of the user IDs being removed and then none being left.  The key works fine in GPG/seahorse, so I'm really not sure how best to diagnose this.  Any help would be much appreciated!!!

[Public key is available on most PGP servers, 0xbbbad6a26c20157a]

**Comment by Valodim** [comment]
Hi. Sorry for the lack of response, we sort of took a break in december and are only now working on the backlog.

So here's the rundown: changing the expiry date of a key in gpg prior to version 2.1.0 breaks the secret key in a way which emerges only on export. It's not a problem with OpenKeychain, we correctly reject the key because its self-certificates are invalid.

This issue has been reported before (#996, #1026), and can be assumed to affect a large number of users. The bug in gpg has been fixed in gpg 2.1.0, but that version is as of now [only deployed in debian experimental](https://packages.debian.org/search?keywords=gnupg2), not even sid. Another [bug report
(https://bugs.g10code.com/gnupg/issue1817) has been opened by jas just today to backport the fix, so I hope this gets fixed soonish.

**Comment by ikelos** [comment]
Hiya, that worked great.  I upgraded to gnupg-2.1.1, exported my keys and they imported absolutely fine.  I can now downgrade to gnupg-2.0 again and carry on as before.  Thanks for solving the problem!  I'm happy to have this closed if you'd like, but I'll leave it up to you in case it's easier for other people to find whilst it's open?

**Comment by dschuermann** [comment]
I started a "Known issue" wiki page: https://github.com/open-keychain/open-keychain/wiki/Known-Issues

**Comment by zanchey** [comment]
Sadly it's been wontfixed upstream; I wonder if there is a way to correctly export the keys at all without upgrading to 2.1.0. Presumably the flags are invalid on all published copies of my key as well as the master copy...

**Comment by Valodim** [comment]
while it is an understatement to say that the keys are "getting out of sync", he is right in that the information is still there and correct in the public key. But: `gpg --export-secret-keys` only exports the secret key, not the public one.

What we could do is keep secret keys we encounter around even if they aren't certified, so that we can use them if we find a certificate for them (from a public key), but that is not a simple change so I can't promise anything.

**Comment by zanchey** [comment]
Understood - many thanks.

**Comment by kolAflash** [comment]
Accepting that GPG-2.0.x does something wrong. Nevertheless the APG Android app seems to be able to handle those private keys exported by GPG-2.0.x.
Would it be hard or bring problems to implement this behaviour for OpenKeychain too?

**Comment by dschuermann** [comment]
APG is simply not verifying the certificates corrently, that's why it "works". It also means that there are attack vectors present in the current APG version. Please consider upgrading GPG to fix this bug.

**Comment by Millak** [comment]
It turns out that if you use gnupg version 1.4.19 (probably all of 1.4.*) also has the bug with gpg --export-secret-(sub)keys, but it does work with gpg2.

**Comment by Valodim** [comment]
yes, that's right. we asked werner to backport the fix, but he refused. not much more we can do about this.
