### ISSUE TITLE
Polish keybase proof UI

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1020]
(been procrastinating this for a while, sorry)

I looked at the keybase proofs, and they are fine technically for the most part. I'm not sure if the perks of having them in a library are worth the slightly less great integration (especially in regards to logging), but that's fine. my main point of concern however is the lack of polish in the ui. missing stuff, in descending order of importance:

* better feedback while a proof is being fetched, like an indeterminate progress bar. right now the ui just freezes completely if connectivity is bad
* change [verify] buttons to right-aligned ones as we have everywhere else
* errors ("proof could not be fetched" and the like) should be reported with a supertoast
* checking of the proof should be a cancelable operation (minor)

I also don't like that evaluation of proofs doesn't really *go* anywhere. The user is shown "ok I verified this" but what does that mean for the key? should the user know himself? in the case where they are able conclude they have some trust for the key, are they supposed to remember this themselves? the mechanism is completely orthogonal to the regular "certify -> green icon" we have everywhere else.

As it is now, I don't think I would include the branch in a release currently (if we even do one)

**Comment by Valodim** [comment]
(forgot to mention @timbray)

**Comment by timbray** [comment]
Well, you said “if we even do one” so it wasn’t clear that I should answer.  I’m quite busy, and I’m not going to invest time in this project if there aren’t going to be any more releases.

With respect to “I also don't like that evaluation of proofs doesn't really go anywhere”.  I think it’s useful to tell the user “@timbray posted a Tweet that could only have been created by the owner of this key”, to help them decide whether they should trust it.  When I demo the app to people they seem to get it right away.

If there’s agreement that this sort of thing is useful, I’m willing to put some more time into UI polish (hah, I’ll have to find a slow network somewhere).  But if the feeling is that proofs don’t really go anywhere and don’t add value, then there’s no point.

The issue of whether previous proof verifications should be remembered is worth discussing.  I thought about that but couldn’t dream up a UX that really added value. You’d really have to squeeze in a date, maybe; the screen gets quite cluttered.  I wonder if that might change if I were on a slow network and so the verification action became expensive.  On a reasonable network, the verification latency is so low that I thought the best UX was just “do the proof, see if it worked in real time.”

Also, certification is much better than it used to be in early 2014 but I still am not convinced it’s comprehensible or useful to ordinary users.

**Comment by timbray** [comment]
Hi, I’ve got a new job that’s been keeping me busy, but I’m taking a 2.5-week vacation in New Zealand in March.  When I’m on vacation I like to do some recreational programming. So, I'd be happy to address @Valodim’s issues above on my vacation, if 

(a) there’s going to be another OpenKeychain release, and 
(b) people think keybase proof verification is worth doing

Up to you guys, of course.  If (a) but not (b), I really think you should take out the mentions of twitter & github & so on on the search/import page (it’s an easy change), because it feels slightly irresponsible to mention them without providing the user the opportunity to verify.

On the other hand, maybe Moxie is right and we should all abandon PGP…

**Comment by Valodim** [comment]
Hey, good to hear from you. Moxie is just being a douche in that blog post. :hurtrealbad:

(a)We are actually planning to release pretty soon, there is way too much unreleased stuff on the development branch. Check out the new KeyView in material design if you havn't seen it yet. We're only halfway there, but it's already amazing. We'll know monday if we are accepted for gsoc so that'll influence things, too.

(b) Dominik recently merged your keybase-proofs branch into development, so it's going to be in the release for sure. The old key view is now the "advanced" view so it's kind of hidden there, but that stuff could be moved to a card, or a certification action or something like that. Can't think of a very natural place for it right now, maybe one of you guys has a good idea

**Comment by dschuermann** [comment]
Hey @timbray ,
As @Valodim said, Keybase verification is under advanced view for now, because we tried to extremely simplify the UI. If you like to work further on keybase support I would propose that we could move it to it's own activity as we have done with "Verify by fingerprint comparison".

If you open a unverified key in Openkeychain right now you will see the general concept of our new design. We highly encourage QR Codes by having this verification on the main floating action button, because they are very usable when meeting in person compared to all other methods we know of. An advanced method is "Verify by fingerprint comparison" which now in the key's menu. There we could also place Keybase verification. Verifying via keybase could then also lead to a certification like done in our fingerprint comparison.
If you like to do this, please consider the usage of cards and implement a progress indication.
BTW: My proofs are not getting verified and a undescriptive error message is shown "Integrity check error". I suspect that's because my key got expired lately. I already updated the validity to "no expiry", so I am not sure what goes wrong there.

**Comment by dschuermann** [comment]
Good enough for now with https://github.com/open-keychain/open-keychain/commit/765ec094c9415fcaddd65b7b743179b2ea7dc098
