### ISSUE TITLE
Send entire keys via QR codes

### ISSUE THREAD

**Issue by xloem** [open-keychain/open-keychain#1078]
For increased security and compatibility, it would be great to transfer entire private and public keys (or even documents) via successive QR codes.

Why?

Exchange via Internet: An internet connection is not always available.  Android is commonly hacked.  Keeping your private key on a phone with an internet connection means the phone may be compromised over that internet connection and your private key stolen.  Instead you could keep a phone in airplane mode, or if paranoid even remove the internal radio.  Additionally, some phones are old and no longer have an active plan.  These phones could now be useful secure devices.

Exchange via SD Card: Not all devices have SD slots.  An SD card from a compromised device may be able to compromise the phone and cache data to break the air-gap.  Additionally SD cards contain a controller chip which can be reprogrammed.

Exchange via NFC: Not all devices support NFC.  NFC radios may have vulnerabilities that could be exploited remotely.  SafeSlinger requires an internet connection.

An alternative to QR codes might be a software modem using the radio and speaker.

**Comment by dschuermann** [comment]
We had this feature in past versions of OpenKeychain. It is mostly impracticable for OpenPGP keys due to their size. For every attached certificate the keyring gets too big to be transmitted by one QR Code. Thus, you need to split the key into several QR Codes. As an example: My key was splitted in ca. 12 QR Codes. This is unusable for average users.

Your arguments may sound valid, in reality they are far fetched. We are trying to build usable OpenPGP software. If you like to keep your private key on a seperate device we suggest to use a Yubikey NEO. Much less hardware that can be compromised and the private key never leaves the device.

**Comment by Valodim** [comment]
> android is commonly hacked

citation needed

**Comment by Valodim** [comment]
Closing note: all of these ideas could be implemented very well with a generic app which registers a send intent, and then on the receiving side broadcast an intent with a mimetype.
