### ISSUE TITLE
Show only those contacts as linked system contacts which have been merged

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1122]
Follow up on #1084
* The "Linked system contact" card should show "none" if the corresponding raw contact of OpenKeychain has not been merged with a "real contact".
* This would be coherent with the behavior of the contact app, which only merges the raw contacts of OpenKeychain into existing ones, as we don't want to pollute the contacts with OpenKeychain keys.

@adithyaphilip You did great prior work on this, if you would like to take this issue, that would be awesome!

**Comment by adithyaphilip** [comment]
I'd love to! :)

From what I understood, when we create a raw contact for a key, we also create a name and an email? Does this end up creating a "real contact" in the contacts app (I think this is what happened on mine)?

One thing we could do is check for an existing "real contact" with the email associated with a key, and only if it exists go ahead and associate a raw contact of the public key with it. If there is no pre-existing contact with a matching email id, we could postpone the introduction of the raw contact containing the public key until the next sync, where again the same check is repeated. This way we can ensure we don't pollute the contact app with contacts associated only with OpenKeychain, which the user does not already have on his phone.

Would this work, or did I misunderstand something?

**Comment by dschuermann** [comment]
There are some mistunderstandings here. We already do not pollute the contact app with OpenKeychain raw contacts. This already works. Raw contacts of OpenKeychain are only displayed when there is a displayed contact where the raw contact is merged into. Except, when the user goes to the contact apps settings and explicitly selects the OpenKeychain account. Then all are displayed. This is the behaviour we want. :)

I would like to see that the "Linked system contact" card only shows the connected contact if a http://developer.android.com/reference/android/provider/ContactsContract.Contacts.html exists, not only a http://developer.android.com/reference/android/provider/ContactsContract.RawContacts.html .
I think you need to check http://developer.android.com/reference/android/provider/ContactsContract.ContactsColumns.html#IN_VISIBLE_GROUP

**Comment by Valodim** [comment]
actually, my contact list looks very polluted right now...

**Comment by dschuermann** [comment]
I just confirmed @Valodim , I was wrong. My contacts are also polluted with OpenKeychain raw contacts. Either we do #1125 or we somehow prevent them from showing up. I think WhatsApp somehow manages to only show them when they are merged with an existing contact. Maybe it is related to IN_VISIBLE_GROUP.

**Comment by adithyaphilip** [comment]
I believe Whatsapp scans your contacts for those with phone numbers matching Whatsapp registered phone numbers, and then associates the Whatsapp raw contact with those matching contacts? If you don't have a matching contact, they let you "add" the number registered with Whatsapp either to an existing contact or a new contact, and then perform the sync again?

I guess in our case our unique identifier is the user's email. We could do the same sync by adding a raw contact only if a pre-existing contact with an email matching the email associated with the public key exists. https://github.com/open-keychain/open-keychain/issues/1125 would probably both prevent pollution and ensure users don't feel a false sense of security with unverified keys. Should we add the email check too?

I was looking into IN_VISIBLE_GROUP - it doesn't look like we can control it directly since it's a read-only attribute. I could explore more, but do the above methods already give us the desired behaviour?

**Comment by dschuermann** [comment]
I think we can close this for now as only verified keys are shown in Android's contacts.
