### ISSUE TITLE
Create key crashes after finish when executed from SelectSignKeyIdActivity

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1123]
Create key crashes after finish when executed from SelectSignKeyIdActivity

**Comment by judeebene** [comment]
Am Jude Ben, Gsoc2105,  am gonna take this , but have created a key and its not crashing, Am using Samsung tablet, Pls Guide on where i can see the bug in my own device

**Comment by manojkhannakm** [comment]
@dschuermann 

This is quite long but please read.

After hours and hours of debugging I've found the root cause this issue. This crash is actually caused due to a NullPointerException.

     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.sufficientlysecure.keychain.operations.results.OperationResult$LogEntryParcel org.sufficientlysecure.keychain.operations.results.OperationResult$OperationLog.getLast()' on a null object reference
            at org.sufficientlysecure.keychain.operations.results.OperationResult.createNotify(OperationResult.java:253)
            at org.sufficientlysecure.keychain.remote.ui.SelectSignKeyIdActivity.onActivityResult(SelectSignKeyIdActivity.java:123)

From what I've understood this is the flow of this process, 
* SelectSignKeyIdActivity
* CreateKeyActivity
* All CreateKeyFragments
* CreateKeyFinalFragment
* KeychainIntentService
* Executes a EditKeyOperation
* Produces a EditKeyResult
* EditKeyResult is parceled and sent to
* CreateKeyFinalFragment and to
* SelectSignKeyIdActivity
* EditKeyResult is unparceled(recreated using the static CREATOR)

While parceling the mLog object in the OperationResult(parent of EditKeyResult) is dehydrated(put into a static Map) and while unparceling the object is rehydrated(removed from the static Map).

This is where the problem is, since SelectSignKeyIdActivity is a Remote API class(usually called from a different ClassLoader), this is having access only to another static instance of the Map which is always empty. So the rehydrate() function always returns null.

This is the debug output after creating two keys from SelectSignKeyIdActivity. This shows the dehydrateMap after parceling and unparceling.

     03-15 09:32:23.081  15657-15657/org.sufficientlysecure.keychain E/Keychain? {49cac3a6-4069-4446-b3a5-f1fc17a2c7b0=org.sufficientlysecure.keychain.operations.results.OperationResult$OperationLog@c857b8}
     03-15 09:32:23.111  15487-15487/org.sufficientlysecure.keychain:remote_api E/Keychain? {}
     
     03-15 09:33:28.491  15657-15657/org.sufficientlysecure.keychain E/Keychain? {49cac3a6-4069-4446-b3a5-f1fc17a2c7b0=org.sufficientlysecure.keychain.operations.results.OperationResult$OperationLog@c857b8, fde63cec-5a89-4e05-aa5d-80f16ad20bc3=org.sufficientlysecure.keychain.operations.results.OperationResult$OperationLog@361a0b6f}
     03-15 09:33:28.521  15487-15487/org.sufficientlysecure.keychain:remote_api E/Keychain? {}

If you see in the second set of output, the log object created in the previous call is still there in the Map.

I also assume this issue exist with other Remote API classes too.

**Comment by manojkhannakm** [comment]
@dschuermann In case if you've missed my previous comment, please check it.

**Comment by dschuermann** [comment]
@manojkhannakm awesome! Thanks for your detailed debugging and work! 
I fixed it in https://github.com/open-keychain/open-keychain/commit/75368034bd620d3d958ba6962f19e82edcb3a562 .
Since these logs are never returned to other apps, the activities should really reside in the same process.
