### ISSUE TITLE
Transifex: help-changelog

### ISSUE THREAD

**Issue by Diapolo** [open-keychain/open-keychain#1172]
Don't be serious with that, because of formatting, you force translators to repeat their job? You should be able to script something, that allows reuse of the old translations... IMHO changelog tramslations are a pain and at least for the german translation was a lot of work! Sorry, I refuse to do that again :-/.

Edit: The same is true for all other HTML files you removed...

**Comment by dschuermann** [comment]
OpenKeychain is heavy work in progress, sry.
The format change was required to ease exchanging help pages between our website and our in-app help.
Even if I script something, I haven't found a tool to re-upload the changed files to Transifex.
I left the changelog translations online in transifex so that you can copy and paste the content over to the new changelog markdown file.

Please consider this: This is a hobby project and we need to move forward.

**Comment by Diapolo** [comment]
Your hobby is also mine, so this isn't working that way... the previous german (changelog) translations were not great and IMHO shed a bad light on the german translation in general.

**Comment by dschuermann** [comment]
So copy and paste from the old changelog files available on Transifex isn't an option for you?

**Comment by Diapolo** [comment]
175 strings only for german... I recently finished the main strings (and there are some issues open, which should be looked at) and currently don't care enough to copy and paste :-/.

**Comment by dschuermann** [comment]
If someone finds out how to convert the html files to markdown and then push them to Transifex, I am open for help.
