### ISSUE TITLE
How to Improve Marketing?

### ISSUE THREAD

**Issue by nuntius35** [open-keychain/open-keychain#1189]
In the past months I have read several posts in forums about the topic (email-)encryption where K-9 Mail & APG were recommended. GIven the fantastic work going on here, I cannot imagine a single reason why someone would want to use APG instead of OpenKeychain. But it seems that OpenKeychain is still unknown to many people. One possible reason might be the Google search results: If you search for something like "pgp android", "gpg android" or "openpgp android" (I know that GnuPG has nothing to do with OpenKeychain, but you cannot expect anyone to know that.) chances are high, that you will completely miss the existence of OpenKeychain, even by looking at all hits on Google's first result page. (I don't know how "personalized" these results really are, but for me I found the word OpenKeychain only on one page, in a blog post by Tom Leister.)

I opened this issue to collect ideas what can be done to spread the word about OpenKeychain. I think it would be sad if people are not using good software like OpenKeychain only because they have never heard about it.

**Comment by Valodim** [comment]
This is an extremely good question.

We planned to announce our releases more aggressively on tech news pages - for that to happen though we need a release first. We have a HUGE pile of changes since the last release (and an accordingly high numbe of bugs), so for now the plan is to get back to a working state on our development branch.

I believe simply asking the authors of the recommending posts you mentioned for an update of their work would help a lot already. I may or may not do that before the release already

**Comment by dschuermann** [comment]
@nuntius35 If you would like to get more involved, we also have this new ToDo: https://github.com/open-keychain/open-keychain/issues/1232
