### ISSUE TITLE
YubiKey FAQ entry doesn't work due bug in GPG 2.1

### ISSUE THREAD

**Issue by tiran** [open-keychain/open-keychain#1190]
Hello,

this isn't a bug at your side but rather a bug in the latest version of GPG. I'm posting it in case somebody else runs into the same issue.

Yesterday I tried to setup OpenKeyChain with YubiKey NEO on my Android phone. I strictly followed the FAQ but I couldn't get OpenKeyChain to work with the key. The app didn't ask me for the NEO key at all and just complained about missing private keys. After about an hour of fiddling I figured out the culprit. In GPG 2.1.2  --export-secret-subkeys and  --export-secret-keys are broken for stub keys. Once I exported with GPG 2.0 everything worked as expected.

I opened a bug report: https://bugs.gnupg.org/gnupg/issue1937

**Comment by Valodim** [comment]
Thanks for your report!

FYI, we have a branch where a lot of work has gone into using Yubikeys more independently from gpg, with support for certification, keyring editing, and ad-hoc import. It's not quite there yet because it involves a lot of rewrites in the crypto backend, but hopefully we can get it into the next release. That should make life with a Yubikey a lot easier.

**Comment by tiran** [comment]
You are welcome!

Are you able to query the "URL of public key" field over NFC? IIRC the public key file plus the key IDs from YubiKey should be sufficient to configure OpenKeyChain.

Keep up the  good work! :)

**Comment by Valodim** [comment]
We are, but that field isn't usually set. But there is the fingerprint field, so that works fine :+1:

**Comment by dschuermann** [comment]
Next release will support YubiKey setup without gpg, thus closing
