### ISSUE TITLE
Multi-threaded key import by CloudImportService Import fails for keyrings with pub+sec key with same key id

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1221]
If we use multi-threaded key import as implemented by CloudImportService the following will happen:

Import fails for keyring with pub+sec key with same key id
- Have a file with separated pub and sec key (as exported by Enigmail for example)
- Import into OpenKeychain

I thought we already fixed this issue at one point in the past, but looks like we somehow re-introduced this bug. So this is a typical case were we _must_ have a unit test.

```
 32096               Keychain  D  insert(uri=content://org.sufficientlysecure.keychain.provider/key_rings/8181922323901784706/user_ids, values=is_revoked=false attribute_data=null is_primary=false master_key_id=8181922323901784706 rank=1 type=null user_id=Dominik Schürmann <d.schuermann@tu-bs.de>)
 32096              SQLiteLog  E  (787) abort at 24 in [INSERT INTO user_packets(is_revoked,attribute_data,is_primary,master_key_id,rank,type,user_id) VALUES (?,?,?,?,?,?,?)]: FOREIGN KEY constraint failed
 32096               Keychain  D  Constraint exception on insert! Entry already existing?
 32096               Keychain  D  android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
 32096               Keychain  D  at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
 32096               Keychain  D  at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:784)
 32096               Keychain  D  at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
 32096               Keychain  D  at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
 32096               Keychain  D  at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
 32096               Keychain  D  at android.database.sqlite.SQLiteDatabase.insertOrThrow(SQLiteDatabase.java:1367)
 32096               Keychain  D  at org.sufficientlysecure.keychain.provider.KeychainProvider.insert(KeychainProvider.java:713)
 32096               Keychain  D  at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:245)
 32096               Keychain  D  at android.content.ContentProvider.applyBatch(ContentProvider.java:1756)
 32096               Keychain  D  at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:297)
 32096               Keychain  D  at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:377)
 32096               Keychain  D  at android.content.ContentResolver.applyBatch(ContentResolver.java:1244)
 32096               Keychain  D  at org.sufficientlysecure.keychain.provider.ProviderHelper.saveCanonicalizedPublicKeyRing(ProviderHelper.java:701)
 32096               Keychain  D  at org.sufficientlysecure.keychain.provider.ProviderHelper.saveSecretKeyRing(ProviderHelper.java:1042)
 32096               Keychain  D  at org.sufficientlysecure.keychain.operations.ImportExportOperation.importKeyRings(ImportExportOperation.java:296)
 32096               Keychain  D  at org.sufficientlysecure.keychain.operations.ImportExportOperation.importKeyRings(ImportExportOperation.java:136)
 32096               Keychain  D  at org.sufficientlysecure.keychain.service.CloudImportService$2.run(CloudImportService.java:277)
 32096               Keychain  D  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 32096               Keychain  D  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 32096               Keychain  D  at java.lang.Thread.run(Thread.java:818)
 32096               Keychain  V  log: LogEntryParcel{mLevel=ERROR, mType=MSG_IP_ERROR_OP_EXC, mParameters=null, mIndent=1}
 32096               Keychain  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_IP_DELETE_OLD_OK, mParameters=null, mIndent=1}
 32096               Keychain  V  log: LogEntryParcel{mLevel=DEBUG, mType=MSG_IP_APPLY_BATCH, mParameters=null, mIndent=1}
 32096               Keychain  E  OperationApplicationException during import
 32096               Keychain  E  android.content.OperationApplicationException: insert failed
 32096               Keychain  E  at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:247)
 32096               Keychain  E  at android.content.ContentProvider.applyBatch(ContentProvider.java:1756)
 32096               Keychain  E  at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:297)
 32096               Keychain  E  at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:377)
 32096               Keychain  E  at android.content.ContentResolver.applyBatch(ContentResolver.java:1244)
 32096               Keychain  E  at org.sufficientlysecure.keychain.provider.ProviderHelper.saveCanonicalizedPublicKeyRing(ProviderHelper.java:701)
 32096               Keychain  E  at org.sufficientlysecure.keychain.provider.ProviderHelper.saveSecretKeyRing(ProviderHelper.java:1042)
 32096               Keychain  E  at org.sufficientlysecure.keychain.operations.ImportExportOperation.importKeyRings(ImportExportOperation.java:296)
 32096               Keychain  E  at org.sufficientlysecure.keychain.operations.ImportExportOperation.importKeyRings(ImportExportOperation.java:136)
 32096               Keychain  E  at org.sufficientlysecure.keychain.service.CloudImportService$2.run(CloudImportService.java:277)
 32096               Keychain  E  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 32096               Keychain  E  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 32096               Keychain  E  at java.lang.Thread.run(Thread.java:818)
 32096               Keychain  D  insert(uri=content://org.sufficientlysecure.keychain.provider/key_rings/8181922323901784706/public, values=key_ring_data=[B@3416a257 master_key_id=8181922323901784706)
```

**Comment by dschuermann** [comment]
Problem has been fixed temporarily here: https://github.com/open-keychain/open-keychain/commit/a45aaa2277422b2bc1521f9237f0ec6c5684bd0c

**Comment by dschuermann** [comment]
@adithyaphilip The fix by me is only temporarily and only for import from files.
For GSoC: There should be only one service for importing keys (CloudImportService), so that we can delete the code from KeychainIntentService and CloudImportService can handle all import cases, may it be multi threaded or sequential.
This should reduce code duplication.

**Comment by adithyaphilip** [comment]
I've verified that changing CloudImportService to sequential instead of multi-threaded resulted in both keys being successfully imported. Seems it's definitely the multi-threading that's causing the issue.
Things I noticed:
* The issue is with just the public key insertion part - I tried importing two copies of the same secret key in the same file and it's the public keyring insertion that fails.
* In my case (exported public + private key from Enigmail in same file), the log said the public key insertion had failed, but turns out the importing of the secret key has taken care of inserting the public key.
* A Thread.sleep(1000) before the second thread is started ensure everything went smoothly.
* Conclusively, the issue arises because both the secret key and the public key being imported try inserting a public key entry at the same time. At the time of checking for existence of a matching public key, both may see false (or just the pub key import may see false, just as bad). This results in both of them trying to insert the same entry later on. I've further verified this by adding a Thread.sleep(1000) just before public key generation in the secret key import. The import of both keys then works.

Possible solutions:
* Enclose our operations in transactions. If the pub key import started the transaction, we wouldn't have to worry about another operation interfering with it. If the transaction fails, we check for the existence of a duplicate public  key and respond accordingly. If it were the secret key ring that started the transaction, our pub key import would be able to detect the existence of the same pub key before it inserts.
* Prevent the situation from arising at all - If we detect operations that would result in possible duplication of the same key being inserted, we order them sequentially. I guess this would be harder to maintain?

**Comment by adithyaphilip** [comment]
Alternatively, since this situation arises only when we're trying to import two or more keys which would end up generating the same key (I see that it occurs even if we import two copies of the same public key) for the same key, we could just check for this condition and make it sequential. Is there any situation where this check wouldn't wouldn't work/wouldn't be possible?
