### ISSUE TITLE
yubikey workflows

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1282]
Thanks to this great pull request #1278  by @josecastillo, there are now mechanisms to a) create yubikey-compatible keys, which is suggested in the manage keys dialog when an empty yubikey is held against the device and b) support in the edit key dialog for moving those keys to the yubikey.

what's missing is a connection between those two. most users should almost never use the edit key dialog, and after a user created a yubikey-compatible key we can assume he wants to move it to his yubikey, so we should offer that option.

this is a little tricky because there are many intermediate states a user might end up in which must be thought about. in particular, what happens if the user creates such a key then stops the procedure?

**Comment by Valodim** [comment]
labeling this discussion for now, we should take a step back and think where we are and where we want to go with yubikeys first. here's workflows we should cover for obtaining yubikey-bound key:

1. user has yubikey with a key on it, wants to import it to openkeychain
2. user has empty yubikey, wants to get it working with openkeychain
3. user has yubikey with a key on it, but wants to create a new one

I think we have 1) covered bar some bugs with special subkey constellations, although dominik had some doubts about the ui flow.

point 2) is almost there with the pull request, except for the missing steps in the wizard (see above).

for 3), my first idea would be to add a "clear key" operation, which does exactly that and leaves the yubikey in a state where flow 2) can be applied again.

there is also the matter of where to ask the admin pin for the yubikey. I'm not sure if the password-cache-flow which is used otherwise is a good idea here.

finally, there is currently no indication that a key is connected to a yubikey in the current ViewKeyActivity (#1252)

btw, does anyone know if yubikeys are shipped in this hybrid pgp+otp state already? I remember I had to change that on mine before I could use pgp features, which was a pretty user unfriendly operation.

**Comment by josecastillo** [comment]
If the user aborts during the key-to-card operation (say, by pulling the Yubikey away after only one or two keys have been processed), their keyring shouldn't be stripped since an IOException will be thrown, preventing the NFC operaton from completing. The user might, however, end up with a Yubikey that has one or two of their keys, but not all three. 

Right now, they can just tap again and it will retry, but that's only because I haven't yet implemented a safety check. Ideally, we should throw an error if the user tries to move keys onto a Yubikey with existing keys, to prevent them clobbering an existing Yubikey with secret keys on it. My suggestion is the following enhancement (pseudocode) in the onNfcPerform case NFC_KEYTOCARD: 

    getData(oldFingerprint)
    if (oldFingerprint == 0000000000000000000000000000000000000000)
        putKey; putTimestamp; putFingerprint(newFingerprint);
    else if (oldFingerprint == newFingerprint)
        return // nothing to do here
    else
        throw IOException("SIG/DEC/AUTH slot already contains a key!")

If a user tries to put a key into a blank slot, the operation will go forward. If the user tries to put a key into a slot that already contains that key, it will silently succeed (allowing for retry if they pulled away before finishing the keytocard operation). If the user tries to put a key into a slot that contains a different key, the keytocard operation will fail rather than clobber the key already on the Yubikey. 

Which brings us to case 3. There is a way to [reset a card to virgin state](https://github.com/Yubico/ykneo-openpgp/blob/master/doc/ResetApplet.txt), such as in the case where a user has forgotten all of their PINs. The procedure is more or less: enter the wrong PW1 and PW3 until they are both blocked, then transmit ```00 e6 00 00``` followed by ```00 44 00 00``` to reset the card. But I'm not sure if that belongs in the on-boarding wizard, since the more common case when a user has a Yubikey with keys on it is that they want to import the keys, not destroy them. 

I'm still not sure about the question of how to prompt for PW3; I need to think about it a bit more.

**Comment by josecastillo** [comment]
> btw, does anyone know if yubikeys are shipped in this hybrid pgp+otp state already?

I'm not sure, but either way, this mode only has to do with how the Yubikey presents over USB. You can actually disable CCID mode and still use the NEO with OpenKeychain, since the NFC interface is separate.

**Comment by Valodim** [comment]
Is there a reason not to upload the key again, even if the fingerprint matches? It seems like the best way to ensure the yubikey ends up in a valid state.

further brainstorming: offering the user to change and save the pin on a first operation or after reset might be a good idea. asking for the yubikey pin for every operation is too inconvenient for most users, but changing the pin and saving it in OpenKeychain gives better protection against an attacker who has access to the yubikey for a short time.

if the openpgp applet is ready to use via nfc, we are getting really close to allowing use of yubikeys with no desktop setup required! yay~

**Comment by josecastillo** [comment]
Since each operation must succeed for the next one to execute, I figured that by setting the fingerprint last, it would act as a check on the atomicity of the operation — i.e. if the sig fingerprint is there, we know that put sig key and put sig timestamp also succeeded. Having said that, I would want to test interrupted operations pretty extensively to make sure that we're putting the yubikey into a valid state, and sending back the right data in the parcel. 

Here's a thought on PINs: if the user taps a blank Yubikey and chooses "smartcard-compatible" mode, we could ask for a PIN instead of a passphrase during setup; encrypt the keychain with that PIN while generating the keys; and then change the card's PIN to that when we're done. The upside is that it's simple to understand (no PIN vs Passphrase confusion), and since the keys will be stripped of secret key material at the end, we don't particularly care that a six-digit PIN is a weak passphrase. The downside, of course, is that if the user wants to back up this keychain, they will probably need a more secure passphrase. 

This still doesn't address the Admin PIN, which is annoying in that we need to change it, yet the user will probably never even use it again. I would even suggest using the same PIN for PW1 and PW3, except for the fact that the Admin PIN has to be at least 8 characters long instead of 6. Needs more thought. 

Definitely excited about getting this working without requiring desktop setup! It's already *way* more accessible the command line minutae involved in setting up a smart card on the desktop :)

**Comment by Valodim** [comment]
We might be able to get away with the assumption that the user is only interested in a one-off setup. For both scenarios 2) and 3) above, we could just clear the key and set the admin pin to whatever.

Users who want special constellations can always use gpg (and will anyways, in all likeliness)

**Comment by dschuermann** [comment]
I implemented rudimentary support for scenario 2) for our key creation wizard in https://github.com/open-keychain/open-keychain/commit/a9c606d49bf7d4e7a30b7265cd1fb04ff1c3c01c
OpenKeychain is now also connected to fresh YubiKey NEOs via https://github.com/open-keychain/open-keychain/commit/7009e504b98d32564c6a9a549d1f5c43959bb24e

**Comment by dschuermann** [comment]
Everything important discussed here should now be available in git master. For everything else: https://github.com/open-keychain/open-keychain/issues/1393
