### ISSUE TITLE
Change keybase strings

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1304]
Instead of post-pending the username the strings should use a variable. This is true for all "keybase_narrative_*"

**Comment by xSooDx** [comment]
I've been trying to work on this for a while, but i can't figure out exactly what to do.
Initially i thought to add '%s' to the keybase_narrative_* strings and use the getString() method to add the usernames but this wouldn't work because it is possible to have multiple usernames.

The existing code seems to work very well as it is. Any change would make little to no improvements.

Could you elaborate so i can better understand what is to be done?

**Comment by dschuermann** [comment]
@xSooDx your approach is right. Use %s instead of prepending the usernames. This should be changed because in some languages the usernames are not at the end of the sentence but in the middle.
