### ISSUE TITLE
Remote sftp keys for double security 

### ISSUE THREAD

**Issue by TiiXel** [open-keychain/open-keychain#1330]
I use OpenKeychain to store my encrypted passwords on Android with [password-store](https://github.com/zeapo/Android-Password-Store). I think this is pretty secure but would my phone be stolen the only remaining wall between potential hacker and my passwords is my passphrase.

Maybe it would be possible not to import all gpg key localy. OpenKeychain could connect to my ssh server where gpg is stored, read the key from distance and give this to password-store. With this, if I lose my smartphone, the only thing I have to do is remove my phone's ssh public key from authorized_keys on my ssh server and I'm fine.

I can use ES File Explorer to browse to sftp and import keys. Then I guess it could do the same whenever I ask for the key !

**Comment by Valodim** [comment]
The feature idea of an externally stored key is pretty interesting. However, this is a very difficult feature to get right, and is only works for very few users, since it requires some technical expertise and trusted online storage (cloud storage providers don't qualify for obvious reasons).

If you want to be more safe, I suggest either using a yubikey, or waiting for the NFC tag feature.

**Comment by TiiXel** [comment]
Well, it's fair to say I did not consider the fact that it's (probably) not easy to program and would be used by very few people anyway. Thank you for considering my suggestion !
