### ISSUE TITLE
Encrypting to all valid subkeys instead of encrypting to just one subkey

### ISSUE THREAD

**Issue by Wikinaut** [open-keychain/open-keychain#1369]
OKC mode: public key encryption to a user, which key has two subkeys for encryption.

I noticed a problem with a public key when **two subkeys for encryption exist**.

### Bug/Problem

OKC appears to use the first subkey-for-encryption, however, I want to encrypt with the second subkey. (remark only: the underlying problem is that the recipient has for some reason only the second private subkey available, because she uses an OpenPGP card, and only the second key-for-encryption/decryption is stored on that).

### Proposal
In the key maintenance submenu (extended key view, where OKC shows the subkeys):
* if more than one subkey for encryption exists, allow the OKC user to select one of the subkeys to be used for encryption

**Comment by Valodim** [comment]
hmm. this solution would be a little finicky implementation-wise, but not too difficult.

the problem with this feature is that it encourages the use of complex keys which require a large amount of understanding from the user to use properly, and this is really what we want to move away from rather than towards. "I want to encrypt to the 'second' subkey" is not a decision any user should ever have to make.

is there a reason why the recipient didn't just use two keys, if they wanted a scenario where the actual ultimate recipient of the message actually differs (if only by the device used)?

a different approach here which goes more in the "it just works" direction would be to encrypt the messages to *all* available and valid sukbeys of a key.

**Comment by Wikinaut** [comment]
> is there a reason why the recipient didn't just use two keys, if they wanted a scenario where the actual ultimate recipient of the message actually differs (if only by the device used)? or did this just emerge as a side effect of using a yubikey, and the original intent was to have the messages available in both places?

It was an unwanted side effect when following instructions from the EFF fellow page creating and copying subkeys (from the master key stored on a safe place) to the OpenPGP card. When strictly following the instructions, there was a second encryption key generated, but the both as part of the key structure were uploaded to the keyservers. A work-around would be to set the expiry date to the past in order to make the one key void.

**Comment by Valodim** [comment]
Subkeys can be revoked, no need to past-expiry-workaround. This does seem to be an acceptable solution otherwise?

still considering encrypting to all encryption subkeys. if properly bound, non-expired and non-revoked, there is no security argument against using both, is there?

**Comment by Wikinaut** [comment]
> still considering encrypting to all encryption subkeys. if properly bound, non-expired and non-revoked, there is no security argument against using both, is there?

encrypting to all encryption subkeys: This is my preferred solution !

**Comment by dschuermann** [comment]
I think there is really no argument against encrypting to all valid subkeys. We should do this.

**Comment by Valodim** [comment]
there are scenarios where the choice of encryption is strictly weaker, like when there is one RSA2048 and one RSA4096 subkey. however, if both are valid, it's not our problem that there is a weakest link.

similarly, a key may have an ECDH key and an RSA one for compatibility, in which case it might make more sense to encrypt to ECDH only.

all things considered though, I think encrypting to all subkeys regardless of their configuration is the most straightfoward and predictable choice here.

**Comment by Valodim** [comment]
discussion over -- make it so.

**Comment by Valodim** [comment]
done in 7648602fc876df3ec5827f3bba1ebbb8ae92eaae

pending unit tests

**Comment by Valodim** [comment]
tests in a320affe862a7ff38ae60bd65f7c73ac8ddcc337

**Comment by Disarate** [comment]
3.4.1 doesn't say anything about #1369. Nothing in FAQ and no changelog on Android appstore. Please confirm that 3.4.1 includes changes of #1369. Regards.

**Comment by Valodim** [comment]
it does. does something not work for you?

**Comment by Disarate** [comment]
This change was not mentioned in app description on appstore. So just wanted to verify. Than you so much. You are the man:)

Regards

**Comment by Valodim** [comment]
happy to help. :+1:

as an explanation for why this isn't in the app store description or in-app help screen: we try to make an app here that can be used without knowing what "messages are now encrypted to all valid subkeys" even means, which is why we avoid mentioning technical tidbits in the user-facing descriptions

**Comment by Disarate** [comment]
Thanks.
