### ISSUE TITLE
OpenPGP error: signing subkey not found!

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1402]
From https://plus.google.com/+EmmanuelBOUAZIZ/posts/SQPHBGhFyC8

```
 
Hello,

I try to use K-9 mail 5.006 and OpenKeyChain 3.3 on a KitKat Android device (custom ROM).

I created the private keys, imported the recipient public key, composed an email, checked sign and cipher, allowed K-9 to access the keys, and when I hit the send button, the following message is displayed at the bottom of the screen:
"OpenPGP error: signing subkey not found!"
I tested with all kinds and sizes of new keys, with keys generated on my laptop, I get the same result.

If I decide not to sign, I get another error:
"OpenPGP error: missing encryption key for %s" (or something like that, the message is displayed in french on my device)

The strangest thing is that when I receive a message, the deciphering and signature verification work correcttly!

Any idea ?
Thanks :)﻿
```

**Comment by ariep** [comment]
Hi!

My friend has exactly the same problem on her device (nexus 7 with cyanogenmod 11), with exactly the same version of K9mail and Openkeychain.

The key was imported from another device, and has worked on other devices for some time without problems.

**Comment by ndavis6** [comment]
Happens to me as well on Cyanogenmod

**Comment by alephex** [comment]
I'm getting the same. The key contains two subkeys (one S, one E). On attempting to sign an email, I get `OpenPGP error: signing subkey not found!`

Android: 4.4.4
K-9 Mail: 5.006
OpenKeychain: 3.3

**Comment by Valodim** [comment]
oh crap, I sort of tracked this one down before but forgot to talk to dominik about it.

the problem here isn't getSecretSignId, that method works as expected. the problem is that the (master) key id in the accounts database is zero. I walked through this with someone on irc, and when he set that field in the database to his master key id manually, everything worked as expected.

**Comment by dschuermann** [comment]
fixed in https://github.com/open-keychain/open-keychain/commit/9c0ec1f4965bd34a05a7a417df51ca470f5f1fae

**Comment by ndavis6** [comment]
Great! Does Travis produce an apk I can test?  I don't know much about building for Android.

**Comment by dschuermann** [comment]
@ndavis6 We will release a new stable version soon, just tuned.

**Comment by Valodim** [comment]
applied fix to database, to avoid problems caused from older versions af546ae10190ac076cd7b091cd064fb8a5c03519

**Comment by petmue** [comment]
To today I imported some keys the very first time on OpenKeyChain: Decryption works quiet fine, but encryption does not work due to the error message mentioned in the opening post.
I use  K9-Mail 5.007 and OpenKeyChain 3.7 from F-Droid on my CM 12.1 (December). 

Are you sure the issue has been completely fixed? 
Please tell me how I can help you to solve this issue (once again).

**Comment by aryoda** [comment]
I observe the same problem as @petmue with K9 5.205 and OpenKeychain 4.2.4.

@petmue 
> by connecting my PGP key to my k9 email account via OpenKeyChain

Can you please post the exact steps through the menus of K9 or OpenKeyChain? I guess you mean K9 and "Settings > Account Settings > Cryptography > My Key" (which is by default "No key selected").

Did you also check the "support signing of unencrypted messages"?

PS: Sorry, I have no keys available on a key server to make this reproducible at the moment... but perhaps other users report the same problem...

**Comment by dschuermann** [comment]
@aryoda please report this at K-9 Mail project. You are commenting on a closed issue here.
