### ISSUE TITLE
Confirm key + upload broken?

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1436]

**Comment by Valodim** [comment]
only the upload is broken, the key is correctly confirmed before that. thinking about this, the upload should probably not be a part of the operation itself, but rather run in the background afterwards, there is no reason the ui flow needs to block until the upload is finished.

**Comment by mohlerm** [comment]
I just tried confirming a friends key. It doesn't matter if we use fingerprint comparison / QR scan or Safeslinger: confirming key doesn't work, the button does nothing.
We didn't tick 'upload' cause we don't want that.

**Comment by dschuermann** [comment]
@mohlerm If you don't check "Synchronize with the cloud" it should work. At least I can't reproduce your problem with 3.4.1.
What version of Openkeychain and Android are you using

**Comment by dschuermann** [comment]
@Valodim I also just tried to reproduce confirm together with upload and it works for me. At least OpenKeychain don't hang or crashes. What exactly have you encountered?

**Comment by mohlerm** [comment]
@dschuermann Sorry for not being specific in the first post.
I'm using 3.4.1 from fDroid on a 5.0 Xperia Z3C. I'm using a masterkey+3 subkey setup and the subkeys are stored on a Yubikey NEO.

Steps to reproduce: 
1. click on a person with a orange question mark symbol
2. Confirm via fingerprint comparison (can't do the others due to lack of 2nd phone atm)
3. Press "Fingerprints match"
4. Select my Key
5. Untick 'Synchronize with the cloud'
6. Confirm key -> Nothing happens
Sometimes a (progress bar?) window flashes for a milisecond, can't read anything on it though.

**Comment by Valodim** [comment]
masterkey+3subkey? can you elaborate on that? or tell us the key id, if it's on keyservers?

**Comment by mohlerm** [comment]
Sure, KeyID: 0x4d90384e53a54380
I've created a signing master key and 3 subkeys: one authentication, one signing and one encryption (sub)key. These three keys are transfered to the Yubikey while the master key is kept airgapped.

**Comment by dschuermann** [comment]
@mohlerm Sry, but lol.
Have you followed a tutorial? If yes can you please send us the URL?
The OpenPGP standard defines that only the master key can certify other keys, thus you cannot certify with OpenKeychain if your master key is airgapped.
However this should show a notification with an error that this is not possible.

**Comment by mohlerm** [comment]
Oh, I actually thought about this being the issue.
I simply wasn't aware that the 'Confirm' dialog in OKC actually represents 'signing' a key...but it makes sense. I suggest adding another form of trust then, something like 'trusted but not signed'. Because I still would like to be able to differentiate between keys I manually exchanged and confirmed and keys I simply imported via a keyserver.

And no, I didn't really follow a tutorial on that, it's pretty complicated and I've been gathering information from lots of different sources.
However mainly:
https://wiki.debian.org/Subkeys
http://forum.yubico.com/viewtopic.php?f=26&t=1171&sid=eae1854ec9f8a69c4f12fe9b1ea8689a
http://forum.yubico.com/viewtopic.php?f=26&t=1344&sid=eae1854ec9f8a69c4f12fe9b1ea8689a
https://wiki.fsfe.org/Card_howtos/Card_with_subkeys_using_backups
https://jclement.ca/articles/2015/gpg-smartcard/

**Comment by dschuermann** [comment]
Regarding notification: https://github.com/open-keychain/open-keychain/issues/1445

**Comment by mohlerm** [comment]
Are there plans to allow a different level of trust like I suggested?
Or would you, not considering the needed effort, not even want this in OKC?

**Comment by Valodim** [comment]
We are not quite happy with the whole "synchronized" deal yet, so the ui flow there will definitely change (hopefully for the better!) at some point.

I'm not really sure what you mean by "confirmed keys you fetched from the keyserver"? Either keys are trustworthy (i.e. confirmed), or they aren't.

**Comment by mohlerm** [comment]
I was thinking about making a difference between trusting a key and signing a key.
So the functionality I propose is that you can 'mark' a key as 'trusted' without actually signing it. This would allow people with a stripped masterkey to use OKC to gather keys by using e.g. NFC and then sign them later using their air gapped machine.
This is obviously not a problem if they key already gained a lot of trust in the 'web of trust' but would be handy for new keys.
However, it's probably not worth the effort since only a few people actually use stripped masterkeys and might also just add another layer of confusion.

**Comment by Valodim** [comment]
We don't support the web of trust at all, and don't plan to. It's a failed concept.

If you want to "mark keys as trusted but not with a specific key", simply create a new key and use it for this purpose only.

**Comment by mohlerm** [comment]
That's actually a very good idea, didn't even think of that. Thanks!
