### ISSUE TITLE
Experimental features setting

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1496]
Create new setting for experimental features on/off

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/commit/ec7a3a704701537eda24afe16081b18b34497928

**Comment by Valodim** [comment]
I thought about this some more and I think I would prefere individual settings for the experimental features. A generic "enable fun stuff" setting which doesn't really say what exactly it does has the same problems as an "advanced mode" setting. people will enable it because they don't want to be missing out.

**Comment by dschuermann** [comment]
done
