### ISSUE TITLE
K-@ Mail

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1500]
got this by mail:

> It is opening the key Association page each time I need to send an email, not just the password pop up after associating the key to the account.

> Problem is happening even with most recent update to K-@Mail Pro https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2

**Comment by countesscvs** [comment]
Thank you, dschuermann. The issue is still extant after recent Open Keychain update, which seems to have caused this bug. After update to your app, when I tap the send arrow in K-@Mail Pro (or even the free K-@Mail) it opens your app. I then choose the key for the associated email address. It usually permanently associates that key to that account so when I tap on the send arrow it goes directly to the pop-up password entry field. On the last update, for every email when I tap the send arrow it opens your app and asks which key,meaning I have to reassociate that key again before it goes back to the K-@Mail email client. Pop-up password entry field then shows on screen. In the past, associating a key to an email accoutrements was done just once, now it is every time. As you know, I am just an end user, not a development professional so I am unable to offer you suggestions. I can only report the bug to you. (And yes, I finally learned how to use GitHub. Ta-da!)
Screenshot of key association Page in your app which comes up each time I tap the send arrow.
![screenshot_2015-09-01-13-34-35](https://cloud.githubusercontent.com/assets/14078434/9611570/6784e264-50ae-11e5-8357-e830b3f3b5cb.png)

**Comment by countesscvs** [comment]
Hi Derek,

In the past two hours I have begun to experience an issue on both emails affiliated with this device (5.0.2) and all 7 emails affiliated with my other device(4.0.4).

Please see screenshots below.It is from the 5.0.2.

I am unable to send or receive, even after updating keys and whether I am on vpn. Can you ascertain the issue? 5.0.2 is on WiFi only with data unchecked. 4.0.4 is on data & WiFi.

![screenshot_2015-09-06-19-53-25](https://cloud.githubusercontent.com/assets/14078434/9707321/c2d91866-54d1-11e5-9ddd-c105fd81aa0d.png)
![screenshot_2015-09-06-19-57-14](https://cloud.githubusercontent.com/assets/14078434/9707322/ca16b34a-54d1-11e5-9ac2-1f063147ce32.png)

**Comment by Valodim** [comment]
Did this last post go in the wrong issue mayhaps?

**Comment by countesscvs** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I am not an experienced git hub user, Vincent.

The issue is with the update. Where, when pressing the send button, the pop-up dialogue box would appear and password entry would unlock and send.Currently, on both my Android 4.0.4 and 5.0.2 the sense button triggers an opening of the Open Keychain app page to choose which key to associate with with which account. This happens for every email sent.

Previously, key association for each account only happened on the initial use of the key with the email account. I am not certain of why this is happening.

Sincerely,

Christina von Siebenbürgen

On Sep 9, 2015, Vincent <notifications@github.com> wrote:
>Did this last post go in the wrong issue mayhaps?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/open-keychain/open-keychain/issues/1500#issuecomment-139078776

- -- Sent with K-@ Mail - the evolution of emailing.
-----BEGIN PGP SIGNATURE-----

iQI+BAEBCgAoIRxMQ1NEKkNWUy5UQUIgPHRhYi5jdnNAZ21haWwuY29tPgUCVfGn
hgAKCRDBx9FIrLKtWxMDD/4ilptKEGZeTK0C8Va7ihlIJOPrtjZgg1uymOWk2lWY
xBEga7t/7JFPvO0pbHl15X4XunQPapecJG5Bjya1k7/YzqRglT36CDh9ga+/Mgez
EWQDajbka5KRzrq3+Pr+McCT7UkboAyqHnWGYQ2n5avanPRSMosJRjXsQswGF18/
bSs49y+riWA72un6BNV/eTipoSeyob7nFTvRvUN/iz2JYeTHK6kC2eGIOSPKxWth
/VFQl2g9ojV8scKm4kfKLMR0Sv/Td9qFYGwntLxpiMhILWgNDt0v6JWNEmVbSykr
9BmCvZ40V67hQgOKH5HaCRyv3GG5Hf/207Jne8IghSZmqDrGYN264gPkmlpzX4fI
/Bg1OVWFp+8AqtG3Cum76GsW+KSmhhSQP54u37gUSmUjUbiDpa/AFLUh4uoksCf8
5V/KZkY6IXnKQVYVdF9+N5NhX7Mg+kIXDVkxZoQn9ZWiyq9/2LQsF5EnT9fAgJmI
nE1dAyj/FKIdokruAhznyXjav1dPgxb9givoZidc72HiYm4uxzlqbjQjNJE7PZsU
z2Dl6wUIBvGRt/YWwouHDy5TvRcxDxqkDGVPRYdGgJeJ1hm1XGSXppbkH0xYCmuY
ukNxH4cRo9r1iXnlhertS/gqF7WRGP9XP0e95umlREVeI7aLDOPH21gEysvY7Kkr
WA==
=pnxa
-----END PGP SIGNATURE-----

**Comment by IBBoard** [comment]
I'm getting the same issue - for maybe a couple of weeks now then OpenKeychain/K-@ Mail doesn't auto-pick the correct key, even though there's one with my email address and I've got K-@ Mail's "try to autodetect key" option selected.

Anything I can do to debug and help?

**Comment by countesscvs** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hey, thanks for acknowledging the same behavior post update.

I am no coder/developer but, I do not believe it is K-@ Mail per se.

It is happening now on both my 4.0.4 (where it first became apparent) and now on my 5.0.2.
The bug does not differentiate between the free and pro versions in this instance.

Could it possibly be due to a glitch in the flow chart direction of the code? Is it repeatedly pointing to the line of code for choose/associate key instead of anchoring to the choice when initially made the first time and holding it as a permanent code string and having the choice remain as unalterable?

To me it just seems that the flow is point to the same string over and over instead of moving forward after first association.  A mistake in the "if/then" run of the string.

At least I do remember that much from my 1980-81 Fortran & Basic computer programming and keypunch class.

Just a thought.

Can any of you line check?

On Sep 20, 2015, IBBoard <notifications@github.com> wrote:
>I'm getting the same issue - for maybe a couple of weeks now then
>OpenKeychain/K-@ Mail doesn't auto-pick the correct key, even though
>there's one with my email address and I've got K-@ Mail's "try to
>autodetect key" option selected.
>
>Anything I can do to debug and help?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/open-keychain/open-keychain/issues/1500#issuecomment-141818321

- -- Sent with K-@ Mail - the evolution of emailing.
-----BEGIN PGP SIGNATURE-----

iQI5BAEBCgAjHBzCqUN2Uy4xIDx0YWIuY3ZzQGdtYWlsLmNvbT4FAlX/PP4ACgkQ
UNn+7xEB6XHomQ/+Li85OGh8wPPhrbf4HcQK8tSro83fSHnVip8PDFYhJOvcY0zM
q7SOjZgeQLZiQqMyu/IU0w0oMQaCj0l/0ebjegOJUAhps7vVzGlPIu/zpy8BJG6H
N840J7q1SjOWagJKq1CrHVWw/mTk0Oows5lgLKwdAjNlndld0KcX17vzEsWPxuVs
Jy8BiF0NVVExVEk2+qoBQGF0J4uauVlIFJHzVCV0mlJcVHQW9r4eBjbfcRalJ4Kd
iyKQCnWSwMFBtjMLOApgIH1YKBMSLObVOHjEOMAq/PoWLwUsEZklWJizNQni5LHR
q8k12EeQ5/M1RNFzC3qLhRK0Hz8jvL/uAEAqeEyjRDVwY5GV0fUyKdUFWk0vHh+s
VTD7CsFGxfsarLkYdNq7y2zWFKK3Y9hOEKMw8C5JjKanTxznRuH1mcKdz8IIbJz8
NsG5lUXeAxYhc24h8ud/iiJudrSckwujU0WPQNMUIG1sMGs2TdU2v/CYobFHT9y8
3peT88L4sP8Kj1kxiQXrHtTCcEz0lT11nSu12p1HCEYhgo66BIN4lks6Zm7QxxYt
5AIDjGaiGjnWw3s7wPiX+R7lQj/dC5FctqWym7s+AB26kU2L37Bkl9kiHyXXyxHy
TMiR94k8geIw1a+I3rlHSmlB+4+b9lKjIkVmXHp9ye9yvKHTnoRGgELiGUs=
=iZQF
-----END PGP SIGNATURE-----

**Comment by countesscvs** [comment]
I am experiencing the issue on Is 5.0.2. Here is info on the new 6.0 OS. https://youtu.be/0hFlBUFwwc4

On Sep 20, 2015, IBBoard <notifications@github.com> wrote:
>I'm getting the same issue - for maybe a couple of weeks now then
>OpenKeychain/K-@ Mail doesn't auto-pick the correct key, even though
>there's one with my email address and I've got K-@ Mail's "try to
>autodetect key" option selected.
>
>Anything I can do to debug and help?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/open-keychain/open-keychain/issues/1500#issuecomment-141818321

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by countesscvs** [comment]
Problem resolved. Thanks. & sorry for the pgp in the posts. I emailed them in, obviously, and did not remember to not auto sign.
