### ISSUE TITLE
Moving existing key to YubiKey NEO

### ISSUE THREAD

**Issue by marix11** [open-keychain/open-keychain#1519]
Hello,

Sorry if its right place to ask. I have sigilance card. How to move key to it. V3.5.1 says feature will be available in upcoming versions. Sigilance doc says to use openkeychain for moving. Is there any older versions which can move keys to smartcards?

**Comment by Valodim** [comment]
Hi,

good question. The feature was disabled in the release because of an unresolved issue regarding admin pins. we havn't got back to it since. I can't tell you how long is going to be since we have a lot of stuff on our plate already for the next release, but hopefully it won't be too long.

(also concerns @josecastillo)

**Comment by marix11** [comment]
Thanks for yoir answer

**Comment by josecastillo** [comment]
Thanks for pinging me on this, @Valodim. I'm hoping to find some time to work on this in the coming weeks.

**Comment by dschuermann** [comment]
@josecastillo I working on something in this direction in https://github.com/open-keychain/open-keychain/tree/create-yubi-key , so let's discuss before you start what is actually missing. I will open a new issue for this.

**Comment by dschuermann** [comment]
Key creation is now available in 3.6. Moving an existing key to a javacard is still disabled, we need to figure out a usable UX for this.

**Comment by slomo** [comment]
I think it is questionable how useful this feature is, given that the default keysize on the phone (4096 bits)  is not supported by current secure elements (eg. 2048 for yubikey).

**Comment by dschuermann** [comment]
Because we moved key editing into the advanced screen, I re-enabled the option to move keys in https://github.com/open-keychain/open-keychain/commit/7b24679094b40c0f99f11d728554bf7c288de24c

Still, it is pretty limited, more discussion here: https://github.com/open-keychain/open-keychain/issues/1845
