### ISSUE TITLE
Slow on S6 5.1.1

### ISSUE THREAD

**Issue by Br3ach** [open-keychain/open-keychain#1535]
Samsung S6, latest 5.1.1 firmware. When I import the key is takes a while at re-importing subkey (?) 90/100. Key seems to be imported OK though. WHen I try to sign to clipboard though I have to wait quite a bit at extracting signature key (10 seconds). Then the app seems unresponsive. Eventually the password prompt appears, then again extracting signature key... 0/100 for 10 seconds.. then success but the overall process takes 30 total to sign one word string... Key is RSA 4096/4096.

**Comment by Valodim** [comment]
you imported your key from gpg, right? can you do `gpg --list-packets` on your exported secret key, and tell me what the "iter+salt S2K" and "protect count" lines look like in there?

**Comment by Br3ach** [comment]
iter+salt S2K, algo: 3, SHA1 protection, hash: 2, salt: 2b1de80a670484f8
protect count: 6815744 (202)

**Comment by Valodim** [comment]
Yeah same problem, this came up a couple of days ago already in #1530. extracting the private key material using the passphrase takes ridiculously long. the extraction algorithm is slow by design, and we're not quite sure how to fix this yet.

try changing the passphrase of your key inside OpenKeychain, that should help a lot already.
