### ISSUE TITLE
switch from passwords to app lock mechanism

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1541]
We had a couple of feature requests in the past for an "app lock" mechanism like many apps have. The idea is to encrypt all application data and require the user to enter a password to access the app at all, with a caching-mechanism just like we have for key passwords now.

We rejected this feature, arguing that:
- the key list isn't really secret, similar to the contacts app the user is better off using FDE if he wants to protect it
- the secret keys are password-encrypted already
- after import from gpg or other tools, the user can use their regular password, which seems like the natural thing to do

At this point however, other arguments have come up which favor app lock over key passwords. The implication of an app lock mechanism is that there is one password to access the app, and after that individual keys are not encrypted again.
- protecting the list of contact keys is actually a very valid use case, especially in repressive countries
- using s2k encrypted keys was adopted from established workflows in pgp, and I feel they stand more on tradition than merit. different passwords for different keys are a feature of questionable use
- moving the password input mechanism from cryptographic operations up to database unlock should significantly reduce code complexity in the crypto routines, which is always a good thing
- hidden recipients are very difficult to implement if we potentially have to ask the user for all key passwords to find the right key to use (#626)
- the s2k mechanism is slow by design, and this is actually becoming a problem for keys which were encrypted on a fast desktop machine (#1530). there are ways to remedy this, but they involve re-encrypting the key so would require password on import

**Comment by Valodim** [comment]
Thought about this some more:

Both "encrypt everything" and "encrypt only my keys" are valid modes of operation, so we will need support for individual encryption of keys. Consequentially, we will need to provide the user with two options: Encrypt the entire database, or encrypt only secret keys. I'm not sure if we should make these independent options, i.e. encrypt database *and* secret keys with different passwords, I tend towards a "no", but leaving this up for discussion for now.

Another decision we will have to make is how to encrypt the secret keys for storage in the database. I think it's a little easier to encrypt them in a container instead of using s2k, because this moves all encryption logic into the database layer, essentially making it part of the key retrieval rather than a property of the key object itself as it is now.

What's nice is that we can split up the implementation into two parts which are almost entirely independent: Firstly, encryption of all secret keys with a (single) master password rather than individual passphrases, and secondly, encrypt the database itself. These are still rather large tasks!

For the former, there are a couple of sub-tasks - in no particular order:
- ask for master password as part of first time wizard
- ask for master password after update if none is set and re-encrypt all keys!
- update secret key import to ask for passphrase, remove it and re-encrypt with master password
- add activity to change the master password (re-encrypting all keys)
- move passphrase/decrypt logic into ProviderHelper, ditch all key s2k handling

**Comment by dllud** [comment]
>  different passwords for different keys are a feature of questionable use

Not so much. When you have keys that are used in different contexts and different threat models  the ability to set up different passwords becomes rather useful. For instance, I might have a key with a 4 digit PIN-like password to sign software releases, another with a simple password to decrypt my email and another with a heavy duty password to secure my Password Store. (I actually use something like this, though with dozens of keys, and imported several of them into OpenKeychain. I know many other developers with similar setups.)

If I had to choose a single master password I would have to go for the heavy duty one. This would hinder the usability of all other keys which don't require that much protection.

Furthermore, it seems that once I entered my master password all my private keys would become ready for use by any app paired with OpenKeychain. I certainly don't want my email app to be able to sign stuff with the software release key. Even if that is not the case, meaning there is some mechanism to select which private keys a given app can access, you would still be increasing the damage potential (DREAD model) of threat exploit: all keys would be available on OpenKeychain's memory instead of a single one.

Also, imagine I am being coerced into revealing a password. In a multiple password scenario I may get away with revealing just the password the coercer is looking for. All other keys are kept safe. On the other hand, with a single master password, they would all get compromised.

Please remember that on PGP each key pair is usually associated with a different entity. Thus it makes sense to keep them as separate as possible. This multiple password mechanism has been used on GnuPG for decades. Departing from it would have other security implications that might be escaping us right now.

Now, looking at the other pros listed for the use of a master password:

> protecting the list of contact keys is actually a very valid use case, especially in repressive countries

You said it: the solution here is FDA. There's little sense in protecting OpenKeychain contacts while leaving all your K9-mail emails stored in cleartext (sender and recipients are always cleartext even on PGP encrypted emails). FDA has such a little overhead nowadays... and it comes with all Android devices. That's what people on repressive countries should use.

> moving the password input mechanism from cryptographic operations up to database unlock should significantly reduce code complexity in the crypto routines, which is always a good thing

IMO, this is the only valid point. Though by itself, code simplicity cannot justify a change such as this one.

>  hidden recipients are very difficult to implement if we potentially have to ask the user for all key passwords to find the right key to use

Asking for all password is not so much of a problem. That's how GnuPG handles this and I see nothing wrong about it. Remember: different keys are used for different identities. Only a few people have several identities, and those are used to input all their password in this scenario. Actually, they probably know which key they should use and can skip the password input on all others.
As hidden recipients are mostly used on Bcc emails there is even a smarter approach: grab the recipient email address from the email headers and try the key for that email first.

> the s2k mechanism is slow by design. there are ways to remedy this, but they involve re-encrypting the key so would require password on import

Here you are coming up with the right solution: re-encrypt the key and change the protected count. Asking for password on import is no big deal.

**Comment by eighthave** [comment]
A few thoughts on this topic, since we've made a few apps that have app-wide encryption and passwords:

* looking at it from the user perspective, OpenKeychain already has a password and caching, so adding full-app encryption can be implemented without changing the user experience at all.  The questions then are of implementation time and maintenance.

* careful about highlighting the multiple-key/multiple-passphrase use cases, that will definitely adversely affect the usability of the much more common single key/passphrase use case.  GPG is a great example of that, it has vast flexibility, and that in turn means it is almost impossible to make simple experiences based it.

* storing the data in an encrypted container is really easy to do if this app already uses only an `android.database.*` SQLite database.  Just use [SQLCipher-for-Android](https://www.zetetic.net/sqlcipher/sqlcipher-for-android/), which is in mavenCentral now, and it'll mostly be a question of changing the imports.  If this app is also using files, then [IOCipher](https://guardianproject.info/code/iocipher) will provide an encrypted virtual disk just for the app (no root required).  Its almost as simple as SQLCipher-for-Android

**Comment by eighthave** [comment]
Also, if you end up using SQLCipher or IOCipher, you might be interested in our [CacheWord]() library for caching AES256 keys.  I'd be interested to hear your thoughts on extending it to also work for the keys that OpenKeychain handles.  Right now, CacheWord was designed around the AES256 keys used for app-specific encryption via SQLCipher and IOCipher.  It would be valuable to pool resources on such critical bits, then hopefully we can also work together on things like easy backup/restore mechanisms, etc.

**Comment by Valodim** [comment]
This is not (only) about an *additional* app lock mechanism. In fact, the app lock aspect is the lowest priority on that list. Currently, the only available workflow is to have secret keys individually encrypted with passwords. Where we want to (ideally) go is:

* as the encouraged workflow, lock all secret keys with a single password/pin/pattern
* as a supported workflow, allow locking of the entire database with a master password/pin
* (optional) as a supported workflow, allow individual locking of keys with a password

As an implementation plan, I would first move from s2k-encrypted secret keys on the pgp object layer to symmetrically encrypted key blocks on the database layer. Secondly, ask for the passphrase and re-encrypt the key on secret key import (required for #1530).

SQLCipher is really only useful for the second use case in the list above, and completely individual from the other two.

Note that none of this is currently very high on the list of priorities, we are mostly documenting our current roadmap and outlook on design choices here.

**Comment by Valodim** [comment]
this is in the works, I'll open a new issue with our current thoughts on this.
