### ISSUE TITLE
Umlauts in filename prevents decrypt from detecting file type

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1544]
Reproduce: 
1. Encrypt Schürmann.pdf
2. Decrypt
3. Not detected as pdf

**Comment by Valodim** [comment]
the mimetypemap will actually trip over various bad characters, like a + as well...

looking at the code brings me to a different thought though: is there even any point to returning the mimetype at all? we guess the mime type from nothing but the filename extension, which we obtain from Android API. I was under the impression that the mimetype might be specified in the pgp data, but that's not the case, so we have no better information in the decrypt routine than the receiver does.

**Comment by dschuermann** [comment]
We have a differentiation between "text/plain" and other mime types due to PGP headers. Also, most applications only register intent filters on mime types and not file endings (we have some nasty hacks to register for specific file endings). So I think we should still try to guess the mime type on our side before viewing stuff.

**Comment by Valodim** [comment]
the problem is with *where* in our code this is happening. to call the intent we need to guess the filetype, but this is the responsibility of the UI code. the backend code should return as accurately as possible what it knows about the decrypted data, no less but also no more. adding a guess about what intent the frontend might want to call with the data breaks separation of concerns, even more so since it introduces `android.webkit.MimeTypeMap` as the only android import besides Context into a `Pgp*` class.

Now OpenPgpMetadata needs to stay backward compatible, so we can't easily remove this field. I would still like to deprecate it, and hand the `b`/`t`/`u` field through directly - because that's the info we actually have at that point.

**Comment by dschuermann** [comment]
Hmmm, I understand where this idea is coming from.
The problem I have with this is that we expose ``OpenPgpMetadata`` via the API and I'd like to have a simple API that requires as little knowledge as possible of the OpenPGP RFC. This is developer usability. We simplify many things over the API and I like to keep it that way so that the risk of doing something wrong security wise is minimized for other app devs.

If we think in longer timespans, it would be great to encapsulate the API inside the client library even more. If we would have such an encapsulation on the client side, I would be again in favor of changing ``OpenPgpMetadata`` as you proposed.

**Comment by Valodim** [comment]
The field leads to false assumptions. I was confused by this because I thought the decryptverify method had better information about the decrypted content than a guess by filename, and I wrote half of that code. To make this clearer we could add documentation that the mime type field is only based on the file extension.

Alas, we are stuck with it for compatibility reasons at this point.

**Comment by dschuermann** [comment]
> I was confused by this because I thought the decryptverify method had better information about the decrypted content than a guess by filename
It has, it knows when its "text/plain"

**Comment by dschuermann** [comment]
I tested it and cannot re-produce this any more in 4.2. Looks like this is fixed with https://github.com/open-keychain/open-keychain/commit/ac4bb3450f4d4f79977ca18d75370c07c207d8df
