### ISSUE TITLE
signing key not found when using k-9 mail

### ISSUE THREAD

**Issue by JoeTac** [open-keychain/open-keychain#1549]
I have generated a set a keys for myself, and when I tell k-9 mail to use open-keychain to sign and encrypt I get "OpenPGP Error: signing subkey not found!"

Can someone help me with this? I have attached some screenshots. If you need more information let me know.

![screenshot_2015-09-29-16-04-07](https://cloud.githubusercontent.com/assets/1260694/10176702/4553c22e-66c4-11e5-8558-8df67e9bc110.png)
![screenshot_2015-09-29-16-04-15](https://cloud.githubusercontent.com/assets/1260694/10176703/4558956a-66c4-11e5-9880-3e349c0e55b7.png)

**Comment by Valodim** [comment]
hi! first of all, thanks for reporting your problem back to us!

can you tell me what versions of k-9 mail and openkeychain you are using?

**Comment by JoeTac** [comment]
K-9 mail - 5.006
Open keychain - 3.5.1

**Comment by Valodim** [comment]
so stable versions all around.

can you try if signing works in openkeychain itself as expected? Encrypt/Decrypt -> Encrypt text -> write some text, choose your key for signing -> share to openkeychain itself and see if it verifies correctly. just to confirm signing still works in general.

also, can you try to remove k-9 from openkeychain and configure it again? as in, go to apps -> k-9 -> context menu (top right) -> "Revoke access", then go into k-9 itself, sign an e-mail and see if it works then.

this issue seems vaguely familiar, but I can't quite put my finger on it...

**Comment by JoeTac** [comment]
Yes. Reconfiguring k-9 with open keychain worked! Thx!

**Comment by Valodim** [comment]
weird, I thought I had fixed this issue in af546ae10190ac076cd7b091cd064fb8a5c03519. hm. well, that part of the api is deprecated anyways, so spending time on it probably isn't worth it.

glad it worked for you.

**Comment by pixelrust** [comment]
Similar keys setup, same error message, same (successful) workaround.

K-9 Mail - 5.010
Open Keychain - 3.9.5

**Comment by haraldh** [comment]
Changed my keys in open-keychain .. same problem, same workaround. Thanks

**Comment by Mebus** [comment]
Hallo,

I am having the same problem. Signing a file works, but I keep getting the "OpenPGP Error: signing subkey not found" error when I try to send an email.

Mebus
