### ISSUE TITLE
Redesign Security Token Import (Yubikey etc)

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1587]
Multiple users have expressed confusion about the import yubikey dialog. A couple of points have come up in irc while discussing the issue:
- The matching public key seems to not be up on keyservers at import time quite often. This either happens because it was created very recently and just isn't there yet (this delay is a general point of confusion with keyservers), or because people don't use keyservers.
- There do seem to be people around who have urls on their yubikeys which we can use. This is encouraged in sjoseffson's [blog post on yubikeys](http://blog.josefsson.org/2014/06/23/offline-gnupg-master-key-and-subkeys-on-yubikey-neo-smartcard/), and quite a few people seem to follow this.
- Users are _not_ aware of what the activity is actually trying to do, which is import the public key. Even users who would have no problem manually importng their public key by some means miss that, simply because we do not indicate it.

I have a suggestion in mind for a design overhaul, will write about it later.

**Comment by Valodim** [comment]
Here's the UI flow I had in mind: The import dialog does not initially offer the user a choice of where to obtain the public key from, but progresses through a list of possible sources. I envision this similar to the UI in the GitHub Linked Identity creation activity, here's a mockup:

![import yubikey mockup](https://dl.pushbulletusercontent.com/UFdUBjyNwWFiDmaeJgFuZplTuYBXuXIA/layout-2015-11-11-161503.png)

The options to "Retry" (makes sense e.g. due to keyserver connection errors) and "From File" show up when all attempts failed.

Things left:
- how can the user "reset" his yubikey and/or create a new key for it?

**Comment by s0crat** [comment]
@Valodim , I'm in the case you suggest in your first message : 
- yubikey with subkeys stored on it
-  URL on yubikey that point to the public master key

Have you been able to deal with this specific import case ?

**Comment by jdanders** [comment]
After two days of searching trying to figure out why my key wouldn't import from my yubikey, I finally found this page. Your opening description perfectly matches my situation -- I presume it's failing because I have not used a keyserver. Before messing around with the yubikey I had no idea what a keyserver was, and I do not really want to upload my key to one because I am still just messing around trying to learn and apparently there's no "delete" button on the keyserver.

I don't entirely understand the PGP approach to life, but if you could add a way to allow my key to be loaded without upload to a keyserver, I would definitely appreciate it. And the app definitely does not help an ignorant user like myself understand why it is failing.

To help google find this page, I'm going to paste my exact error below:
```No keys found!```
(I click on "DETAILS")
```
Retrieveing from keyserver: [my key]
Could not retrieve key from keyservers: not found
Key could not be retrieved! (Network problems?)
Import operation failed!
```

**Comment by pnorton** [comment]
> There do seem to be people around who have urls on their yubikeys which we can use. This is encouraged in sjoseffson's blog post on yubikeys, and quite a few people seem to follow this.

Can more detail be added about this statement?  I'm trying to understand the relationship between the url and the issue at hand. 

Is there a known workaround for this?

**Comment by Valodim** [comment]
I afraid I don't quite understand the question :)

"the url" is a text field on the yubikey which is intended to point to a location where the public key can be found. This is in no way automated by any software I'm aware of, so the reliability of this method of discovering the public key is very low.

**Comment by pnorton** [comment]
To clarify-- Are you referring to the "URL of public key" found in the smartcard implementation of the yubikey?  as see below?

`user@debian:~$ gpg --card-edit

Application ID ...: D2760001240102000060000000420000
Version ..........: 2.0
Manufacturer .....: unknown
Serial number ....: 00000042
Name of cardholder: [not set]
Language prefs ...: [not set]
Sex ..............: unspecified
**URL of public key : [not set]**
Login data .......: [not set]
Signature PIN ....: forced
Key attributes ...: 2048R 2048R 2048R
Max. PIN lengths .: 127 127 127
PIN retry counter : 3 3 3
Signature counter : 0
Signature key ....: [none]
Encryption key....: [none]
Authentication key: [none]
General key info..: [none]`

Or are you referring to a URL field in the yubikey itself that it separate from the smartcard\PGP key?

**Comment by Valodim** [comment]
Yes I am referring to this url field

**Comment by kirelagin** [comment]
I’m having a hard time trying to import my key from a YubiKey too.

When I tap the YubiKey OpenKeychain asks for the public key. I have a file with the public key (which I downloaded myself since OpenKeychain ignores the URL field), but it does not help: the key does not appear in “My Keys”, it appears as a key of some other contact, and I can‘t use it to decrypt. What am I missing?

**Comment by viorels** [comment]
I've had the same problem. You have to import the private key stub, not the
public key. Let me know if you need help exporting that from your computer.

Viorel

**Comment by kirelagin** [comment]
Thanks @viorels, that did the trick!
Not very intuitive :(. This means that I can’t start using a YubiKey if I do not have a computer to create stubs.

**Comment by Valodim** [comment]
That is incorrect. If you have the public key imported, and you hold the key to your device, you should get a card that allows you to bind the public key to your token. But yes: our workflow for this is imperfect, which is why this issue exists.

**Comment by kirelagin** [comment]
> you should get a card that allows you to bind the public key to your token

Well, I suspected that it could work this way and tried to do that, but got nothing. This is probably due to some other issue that makes OpenKeychain refuse to decrypt anything, saying that the token does not contain the required key (although it clearly does as I can use it on my computer), which I have yet to investigate.

**Comment by Valodim** [comment]
Work in progress in #2157
