### ISSUE TITLE
Limit create key options / redesign subkey creation dialog

### ISSUE THREAD

**Issue by JasperWeiss** [open-keychain/open-keychain#1600]
Openkeychain offers the option to use an 8192 bit RSA key. I figured I might aswell use that. But it seems people reccommend not to use it because it adds extreme ammounts of overhead and is considered overkill.
Is it? 
And if it is, why does Openkeychain offer it as an option?

**Comment by Valodim** [comment]
Some people do love this feature, and create 16k RSA keys and feel really good about their feeling of increased security.

I agree: We should remove it.

**Comment by JasperWeiss** [comment]
I have to admit I barely see any performance hit. Should I revert to 4096? I haven't used/uploaded it yet because I'm still experimenting with it. I'm stil not sure whether I should use RSA, 4k, 8k, Elliptic curve etc. I know RSA 4k is recommended but I was curious if anything higher/different might be recommended a few years in the future.

**Comment by Valodim** [comment]
even rsa 4096 has a fair margin of healthy overkill to it. check out http://keylength.com

**Comment by dschuermann** [comment]
@Valodim Before we remove this feature: After edit key refactorings, this will be pretty hidden anyway.

If we start removing support for RSA > 4096, it's pretty hard to argue why not simply remove every key creation option besides RSA 4096, ECDSA P-256, and ECDH P-256. All other options are questionable.

**Comment by Valodim** [comment]
RSA2048 is used on security tokens, but yes everything else is questionable

**Comment by dschuermann** [comment]
Still RSA 2048 must not be available via UI :D so even that one...
I am not sure if we should go down this road. As always, I like to have a balance between flexibility and usability. Maybe we can simply move that even more into the advanced screens.

End-to-End is always the extreme example for me, where there aren't even advanced screens to add RSA keys (at least in the last version I saw). Maybe that's going too far.

**Comment by JasperWeiss** [comment]
I feel most users would go with the default configuration. People who specifically change the configuration to anything else probably know what they're doing. Isn't free-open-source software about giving users flexibillity and control? Perhaps we could hide the other alhorithms/key sizes by default and show an option in the configuration menu like "show advanced options"

**Comment by dschuermann** [comment]
If no one has an objection, I would close this issue. Key creation is now only available in the advanced screen.

related:
https://github.com/open-keychain/open-keychain/issues/1657

**Comment by Valodim** [comment]
I still think we should get rid of 8192 keysize. why? because of exactly the scenario @JasperWeiss mentioned, "I figured I might as well use that". 8096 keys are simply not a valid use case, and we do users a disservice by even mentioning it. if someone really wants to do unreasonable stuff, there's always gpg.

**Comment by dschuermann** [comment]
Just to understand your exact position:
As I outlined earlier, what options do you want to expose to the user in this dialog?
If we only expose recommended ones we end up with:
Algorithm: RSA, ECDSA, ECDH
curves: P-256 (do we even need P-512?, it's overkill)
RSA sizes: 2048, 4096
usage: certify, sign, encrypt
(remove expiry option)

**Comment by JasperWeiss** [comment]
The expiry option might be something people would want to use, we should keep it available under the advanced section.

**Comment by dschuermann** [comment]
@JasperWeiss Unfortunately, the discussion which options to expose to the user and which not is really difficult. I am okay with how it is now in git master together with changes proposed in #1657.

I personally recommend against expiry, see https://github.com/open-keychain/open-keychain/wiki/OpenPGP-Security#no-expiry-for-keys-created-by-openkeychain

**Comment by Valodim** [comment]
How about offering options with a short summary of its properties? For example:

* RSA 3072 (considered secure until 2040)
* RSA 2048 (smaller filesize, considered secure until 2030, can be stored on YubiKey)
* ECDH (very small filesize, considered secure until 2040, experimental and not supported by all implementations(!))
* ECDSA (very small filesize, secure until 2040, experimental and not supported by all implementations(!))

(This is from what I remember from the ECRYPT recommendations from the top of my head, some or all of that info may be arguable, so data just for example's sake.)

**Comment by dschuermann** [comment]
@Valodim I really like this idea, awesome!
We need to discuss some details of it, will talk tomorrow.

**Comment by Olf0** [comment]
The topic "supported key sizes and algorithms" has been discussed oh so many times, e.g. in the context of Gpg4win and GnuPG.  I believe the outcome is a good guideline. 
For GnuPG there is a whole chapter (11) WRT this topic in the FAQ <https://gnupg.org/faq/gnupg-faq.html#advanced_topics> and an extra page in the GnuPG wiki with reasoning: <http://wiki.gnupg.org/LargeKeys>  
Additionally one can find quite some discussions on public mailing lists and forums, which all evolve basically the same way.  Examples:  <http://www.gossamer-threads.com/lists/gnupg/devel/63913> (typical), <https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=137824> (the oldest I know), <https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=739424#30> (in depth and fiercely), <http://www.gossamer-threads.com/lists/gnupg/users/63390> and many, many more. 
Exactly the same applies to Gpg4win. 

From an developer's perspective there are two lines of thought: 
- "Freedom for the users": Provide many choices and let the users decide, in order to keep the number of feature requests for more options small.  But history has shown, that this concept leads to serious interoperability issues (hence creating bug reports instead of feature requests) and people still regularly cry for longer keys (and sometimes for special algorithms). 
- "Interoperability and Guidance for the users": Well, this is already the track you are on, and IMHO that is the only way to go for a GUI application targeting a broad range of users.  But be prepared for being regularly questioned to defend what OpenKeyChain offers and what not.  Thus having an entry in OpenKeyChain's FAQ outlining your line of thoughts may ease your communication labour.  Additionally owning a set of external references (e.g. GnuPG FAQ chapter 11, the public recommendations by NIST (USA), ANSSI (France) and BSI (Germany, [1]), etc.) may be helpful for fierce mailing list debates.  

For the specific supported key sizes and algorithms, I think dschuermann's post "If we only expose recommended ones we end up with:" is an excellent starting point. 
- RSA-2048 is a must for interoperability (e.g. key migration to another cryptographic software) and is still the common denominator of modern smartcards. 
- Please take also RSA-3072 into account, as this is the largest key size most of those smartcards chips support, which support more than 2048 bit keys. 
- 4096 bits should be the largest RSA key size offered in the GUI, as longer keys definitely will not be interoperable.  Even longer RSA key sizes offer very little (e.g. see GnuPG FAQ chapter 11.5), but vastly extend the computation times when using such a key.
- Do not set RSA-4096 as default!  People will ask why they can choose only something lower than the default and there is currently (as of 2016) no reason for it.  I suggest still defaulting to RSA-2048 this year and reevaluate switching the default to RSA-3072 maybe annualy.  And still many years ahead one will want to take ECC as default into account. 
- Although there is currently no practical reason to offer P-512 (along P-256), people will ask for at least one "stronger" EC choice.  As the computation times for ECC are much shorter than for long RSA keys and P-512 is properly specified plus widely implemented (although I am not sure how widely), I would go for it.
- The expiry option has its valid use cases (which cannot achieved without it), thus people will ask for it and IMO it is hard to reason to ditch it. 
 

Reference 1: <https://www.bsi.bund.de/DE/Themen/DigitaleGesellschaft/ElektronischeSignatur/TechnischeRealisierung/Kryptoalgorithmen/kryptoalgorithmen_node.html> (in German)

**Comment by dschuermann** [comment]
@Olf0 Thanks for your detailed comment, it really helped. We are now thinking to make the dialog a teo step process:
1. screen: a list with checkboxes including: RSA 2048, RSA 3072, RSA 4096, Elliptic Curve P-256, Elliptic Curve P-521. Under these headlines a short description is shown like proposed by @Valodim . We will not differentiate between ECDH and ECDSA at this point. On the bottom the buttons Cancel and Next.
2. screen: A way to select the flags (not completely decided yet). Selecting the sign/certify flag will result in ECDSA keys for ECC and encrypt in ECDH keys for ECC. Under the flag selection, the expiry is shown (unchanged to the current implementation).

This is still subject to change.

**Comment by AlexFJW** [comment]
Some notes to add after discussing with Valodim.

We should be able to keep to a single screen multistep process, rather than use 2 screens. Screen will use a drop down menu for algorithm/keysize, followed with radio boxes for usage configurations (as opposed to check boxes), and keep what we currently have for expiry.

Algo/Keysize:
Keeping algorithm/keysize hidden as a dropdown might be better than giving a screen to it, increasing the likelyhood of new users sticking to the default. 

Usage configurations:
Radio boxes will be used to simplify the options available. Authentication will be omitted since open-keychain doesn't provide authentication related features.

The following is a (rough) mockup to provide a clearer picture:
[https://cloud.githubusercontent.com/assets/11351531/13895713/d39e0278-edb1-11e5-91c9-eb88ddc58043.png](https://cloud.githubusercontent.com/assets/11351531/13895713/d39e0278-edb1-11e5-91c9-eb88ddc58043.png)
[https://cloud.githubusercontent.com/assets/11351531/13895714/d4814e70-edb1-11e5-808d-27355ad72c4d.png](https://cloud.githubusercontent.com/assets/11351531/13895714/d4814e70-edb1-11e5-808d-27355ad72c4d.png)

**Comment by dschuermann** [comment]
jup looks good!

**Comment by Olf0** [comment]
Looking really good.

Two comments WRT the text for "ECC P-521":
- The wording for its durability is different than for all other algorithms.
- With "2040" for its durability, people will perceive it as weaker than "RSA 4096" and of the same strength as "ECC P-256".

Hence I suggest changing the text for "ECC P-521" from 
   ..., secure until 2040, ... 
to 
   ..., considered secure until 2040+, ... 

On 19 March 2016 02:09:39 CET, Alex Fong Jie Wen <notifications@github.com> wrote:
> [...]
> [https://cloud.githubusercontent.com/assets/11351531/13895714/d4814e70-edb1-11e5-808d-27355ad72c4d.png](https://cloud.githubusercontent.com/assets/11351531/13895714/d4814e70-edb1-11e5-808d-27355ad72c4d.png)

-- 
Ciao 
   Florian

**Comment by AlexFJW** [comment]
Ah my bad, accidentally missed that out.  Thanks for catching that :)

**Comment by Olf0** [comment]
Sorry for the late second thought, still WRT the texts in the algorithm selection window.
Line of thought is, "What incentive is provided transparently (i.e. in the text) to an user *not* to just decide between RSA and ECC, followed by picking the strongest available algorithm, because 'that is the best I can get'?": 
- In order to maintain the structure of the text for "RSA 2048", you may prefix the text of "RSA 4096" with "larger filesize, ...". 
- In order to differentiate between "ECC P-256" and "ECC P-521" you may change the text for "ECC P-256" from "very small filesize" to "extremely small filesize".  Or for "ECC P-256" to "very tiny filesize" and for "ECC P-521" to "tiny filesize".  Or ... you get the idea: Differentiate between the two ECC algorithms and stay away from the terms used for RSA. 


On 20 March 2016 02:11:36 CET, Florian Samson <mobil@fsamson.de> wrote:
> Looking really good.
> 
> Two comments WRT the text for "ECC P-521":
> - The wording for its durability is different than for all other
> algorithms.
> - With "2040" for its durability, people will perceive it as weaker
> than "RSA 4096" and of the same strength as "ECC P-256".
> 
> Hence I suggest changing the text for "ECC P-521" from 
>    ..., secure until 2040, ... 
> to 
>    ..., considered secure until 2040+, ... 
> 
> On 19 March 2016 02:09:39 CET, Alex Fong Jie Wen
> <notifications@github.com> wrote:
> > [...]
> >
> [https://cloud.githubusercontent.com/assets/11351531/13895714/d4814e70-edb1-11e5-808d-27355ad72c4d.png](https://cloud.githubusercontent.com/assets/11351531/13895714/d4814e70-edb1-11e5-808d-27355ad72c4d.png)

-- 
Ciao 
   Florian

**Comment by AlexFJW** [comment]
That's a really valid point there. Thanks for the thoughts. I'll go with the following for now. 
- smaller filesize, considered secure until 2030, can be stored on YubiKey
- recommended, considered secure until 2040
- larger file size, considered secure until 2040+
- tiny filesize, considered secure until 2040, experimental and not supported by all implementations(!)
- very tiny filesize, considered secure until 2040+, experimental and not supported by all implementations(!)

**Comment by Olf0** [comment]
That's looking excellent!

NB: Note that you swapped "tiny" and "very tiny": It should be "very tiny filesize" for "ECC P-256" and "tiny filesize" for "ECC P-521".

On 21 March 2016 00:52:37 CET, Alex Fong Jie Wen <notifications@github.com> wrote:
> That's a really valid point there. Thanks for the thoughts. I'll go
> with the following for now. 
> - smaller filesize, considered secure until 2030, can be stored on
> YubiKey
> - recommended, considered secure until 2040
> - larger file size, considered secure until 2040+
> - tiny filesize, considered secure until 2040, experimental and not
> supported by all implementations(!)
> - very tiny filesize, considered secure until 2040+, experimental and
> not supported by all implementations(!)
> 
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/open-keychain/open-keychain/issues/1600#issuecomment-199061573

-- 
Ciao 
   Florian

**Comment by dschuermann** [comment]
has been implemented, closing.
