### ISSUE TITLE
Support Curve25519 encryption

### ISSUE THREAD

**Issue by dllud** [open-keychain/open-keychain#1627]
Encryption with Curve25519 should be added as a companion for Ed25519 #1533 signing.

[GnuPG 2.1.7 (August 2015) now ships with Curve25519](http://www.gniibe.org/memo/software/gpg/keygen-25519.html) and will [use it as default](https://www.gnupg.org/faq/whats-new-in-2.1.html).

It would be great if OpenKeychain follows along. That way we can have interoperable implementations getting past the NIST and Brainpool curves' doubts. This effort would help future standardization.

There is already a Curve25519 implementation on Bouncy Castle: [org.bouncycastle.math.ec.custom.djb.Curve25519](https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/math/ec/custom/djb/Curve25519.java)

**Comment by dschuermann** [comment]
yup that would be nice. We are open for pull requests for this one.

**Comment by Zeitwaechter** [comment]
+1

The crypto talks at the 32C3 - the annual international hacker community event of the Chaos Computer Club - in Hamburg, Germany, did show (again) how important an upgrade to higher encryption would be.
But.. Even though - estimations are that ECDSA/Curve25519 is supposed to be also done in probably about 10-15 years thanks to the work of the NSA and computer technology.
(If Curve25519 is really as secure as everyone thinks it is. Doubts included.)
And I do think this will happen sooner than later.
A very big problem for folks who still don't use private E-Mail Servers/Domains.

So anyways!
It would be nice to see anyone helping out.
Otherwise I'll have to rethink how to actually write mails via Android.

Thank you very much in advance! :)

Greetings!

PS:
Obviously we all know that closed hardware is another very big problem. 
But one problem after another, right?

**Comment by dalmia** [comment]
Hi! I am a newbie and want to contribute. I have been trying to understand the code structure but am finding it difficult to merge the pieces together. I have the app running and am trying to understand the flow now. But I have never worked with such a large codebase, so can you ease me through understanding the code better?

**Comment by Valodim** [comment]
If you have concrete questions about some parts of the code, feel free to ask on the mailing list.

Also note that this is one of the more difficult issues, if you aren't experienced in crypto algorithms and algorithmic coding, starting somewhere else might save you a lot of frustration.

**Comment by gaenserich** [comment]
A big +1 from me, too.

**Comment by Valodim** [comment]
Closing this issue, will open a new one with updated information on this.
