### ISSUE TITLE
EncryptKeyCompletionView: Deleting a token shows class name

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1636]
1. Add 4 keys to EncryptKeyCompletionView
2. Focus other textview, now it is shown as "Test +3"
3. Focus EncryptKeyCompletionView. delete token:

![device-2015-12-22-142501](https://cloud.githubusercontent.com/assets/321888/11956130/241fbd70-a8b8-11e5-9cc7-b31f676abacf.png)

**Comment by rohands** [comment]
I'm working on this

**Comment by rohands** [comment]
I think the problem to be addressed was to not get class name on trying to delete the token after the focus had been changed atleast once. 
After quite some debugging I figured that it was calling KeyItem's toString() method. Whatever text is returned from toString() would appear when the token is deleted. 
The workarounds are 
1. You can set a certain deletion style by which only the text that was entered by the user before the token had been matched would remain on deleting the token OR 
2. The more obvious way by which you can make no text appear by deleting the token. (Default behaviour)

However I'd like to bring to your notice that there's a flaw in my code. 
You might be wondering why I've returned " " ( string with whitespace and not an emptry string) from toString() of KeyItem class.
Well that's because on returning an empty string I'm not sure how but it seemed to have been conflicting with the functionality of the library. The "token matching" wasn't happening. 
But then, leaving things at a whitespace pretty much solves the problem right? The user will have to delete an extra character in contrast to the several characters which would appear in case class names appeared.

I'd like to know where I went wrong in understanding.
Thank you

**Comment by dschuermann** [comment]
@rohands You are right, your patch actually worked as a workaround. I have applied it in https://github.com/open-keychain/open-keychain/commit/4c0240dd6c67c597b2b8f365d794203868eb7d6c . Previously I had problems applying your pull request because it wasn't in a proper git branch, so I overlooked the whitespace in toString.

I still think we should find a proper solution to this problem, having the user to delete whitespaces is not great.

@Valodim Have you used TokenAutoComplete in K-9 Mail? Have you encountered this problem?

**Comment by Valodim** [comment]
Yeah, this is sort of a known issue, I didn't get to fix it yet. This occurs after a token is redrawn, because the widget forgets the string which was used to create it and uses `toString` instead - which is the memory address by default. I also don't think we should use `TokenDeleteStyle.ToString`. Will look into it more, this will do for now I guess.

**Comment by dschuermann** [comment]
Added an issue in their bug tracker here: https://github.com/splitwise/TokenAutoComplete/issues/195

**Comment by Valodim** [comment]
submitted a PR for this: https://github.com/splitwise/TokenAutoComplete/pull/212
