### ISSUE TITLE
QR Code fullscreen: landscape broken

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1644]
QR Code is not properly resized in fullscreen.

**Comment by unyoungwax** [comment]
In `qr_code_capture_activity.xml`, `zxing_framing_rect_height` and `app:zxing_framing_rect_width` are set to a fixed value so that the frame is a square in both portrait and landscape orientations. `300dp` is chosen as the fixed value because it is close to the size of the frame in portrait orientation before this change.

```xml
<com.journeyapps.barcodescanner.CompoundBarcodeView
        android:id="@+id/zxing_barcode_scanner"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_alignParentBottom="true"
        app:zxing_framing_rect_height="300dp"
        app:zxing_framing_rect_width="300dp"/>
```

**Comment by dschuermann** [comment]
Oh, I mean the display of QR Codes not scanning of QR Codes ;)

**Comment by unyoungwax** [comment]
In `qr_code_activity.xml`, using `ImageView` with `android:scaleType="centerInside"` can resize the QR code properly. `AspectRatioImageView`(a subclass of `ImageView`) will be rendered redundant.

```xml
<ImageView
    android:id="@+id/qr_code_image"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:scaleType="centerInside"/>
```

**Comment by dschuermann** [comment]
Please test on different Android versions starting from Android 4.1 and make a proper pull request.
