### ISSUE TITLE
Key import from file broken since Facebook support pr

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1664]
Importing keys from files no longer loads the keys inside the import activity's list. Reverting https://github.com/open-keychain/open-keychain/commit/f29280bbb268d112426c6662e1227118819fb904 solves the issue.

@adithyaphilip Can you look into this?

**Comment by adithyaphilip** [comment]
Figured it out - side-effect of having `handleActions` in `onResumeFragments`. `onActivityResult` is called before `onResumeFragments`, so the fragment it loads with the key data from the file, ends up being replaced by the latter.

This also meant that if a user minimizes the app after a cloud search the results would be wiped and he'd have to search again.

Fixed with https://github.com/open-keychain/open-keychain/pull/1666.
