### ISSUE TITLE
sync only when unmetered internet is available?

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1670]
This can probably be answered by @adithyaphilip: what are our current considerations for internet availability for key sync? If a user has a lot of keys, since we have to download the entire key to find if new content is available, it's quite possible that we sync relevant amounts of data (i.e. 1MB+). Do we currently restrict the key sync operation to a time when unmetered internet is available? Or would it also be run on mobile data?

I might have missed a conversation on this topic, but @dschuermann didn't know either. Has this been considered?

**Comment by adithyaphilip** [comment]
Nope, we hadn't considered that at the time. Right now we're only run if the user has an active internetconnection, but that's pretty much it. So unless the user has restricted background data we run on mobile data too.

We could check if the user is connected to an unmetered WiFi network, failing which we could postpone the sync by say, three hours? There is however the issue of if both mobile and WiFi are connected, we may not be able to predict which connection Android decides to use. What should we do in that case?

**Comment by Valodim** [comment]
Hmmm, yeah that seems like the way to go. Checking wifi state requires a new permission though :(

**Comment by dschuermann** [comment]
This is really difficult to get right. There is an article on http://developer.android.com/training/basics/network-ops/managing.html#manage-usage that implements settings similar to those available in Google Play's settings screen for auto-updating apps. However, even if we would implement something like this, what should we do if a user has "only on wifi" and then never connects to one? The keys will get old...

@Valodim ACCESS_NETWORK_STATE is automatically granted on Android 6 and I think it is also one of the "other" permissions no longer shown in Google Play.

**Comment by Valodim** [comment]
You're right, it's a [normal](http://developer.android.com/reference/android/Manifest.permission.html#ACCESS_NETWORK_STATE) permission. "Only on Wifi" but user is never on wifi seems like an edge case, I wouldn't consider it for now.

**Comment by advaita13** [comment]
Ignoring the edge case it should be straightforward to implement a "Sync Only Over Wifi" preference. If option is checked and there is no wifi connection sync can be postponed by a given time interval.

Much of this is already implemented in the KeyserverSyncAdapterService class for Automatic Key Updates. I can give it a try if this solution is acceptable.

**Comment by adithyaphilip** [comment]
@advaita13 If an update is pending, you could register a broadcast receiver for for when WiFi gets connected (more on that <a href="http://developer.android.com/training/basics/network-ops/managing.html#detect-changes">here</a>). As mentioned in the link, you should consider using <a href= "http://developer.android.com/reference/android/content/pm/PackageManager.html#setComponentEnabledSetting(android.content.ComponentName, int, int)">setComponentEnabled</a>, to listen for the broadcast only if we've miss an update due to lack of WiFi connectivity, and disable it suitably afterward.

**Comment by advaita13** [comment]
@adithyaphilip Noted. This would be the most efficient way to handle the problem and also a great place for me to start. Thanks.

**Comment by advaita13** [comment]
Have made the requested changes. Problem is how to testing. Anyone got any ideas?

**Comment by adithyaphilip** [comment]
The `KeyserverSyncAdapterService` has constants that let you control how often an update happens.

**Comment by advaita13** [comment]
How do I know if the keys have been updated or not?

**Comment by adithyaphilip** [comment]
You could `Log` the part of the code that downloads the keys in the service.

**Comment by advaita13** [comment]
@adithyaphilip Eliminated most of the bugs however I am stuck since a long time at one particular issue.

`public void setWifiComponent(Boolean isEnabled, Context context){

        PackageManager pm = context.getPackageManager();`

There is a problem with the context as KeyserverSyncAdapterService isn't part of an activity thus there is no context. Tried passing getContext() and getApplicationContext() as well. Keep getting Null Object Reference exception.

**Comment by dschuermann** [comment]
A Service extends Context, so there is one ;)

**Comment by advaita13** [comment]
Thanks. Also, this keeps popping up...

> java.lang.RuntimeException: Unable to instantiate receiver org.sufficientlysecure.keychain.service.KeyserverSyncAdapterService$NetworkReceiver: java.lang.InstantiationException: java.lang.Class<org.sufficientlysecure.keychain.service.KeyserverSyncAdapterService$NetworkReceiver> has no zero argument constructor

Declared a no-argument blank constructor for NetworkReciever and even KeyserverSyncAdapter but still no luck.

**Comment by dschuermann** [comment]
Can't help you with that. You need to debug that by yourself :)

**Comment by advaita13** [comment]
The service crashes when I turn off Wifi, still works as it is supposed to despite the crash. Here's what the logs say...

> W/ActivityManager: Wtf, activity ActivityRecord{ee1aad4 u0 org.sufficientlysecure.keychain.debug/org.sufficientlysecure.keychain.ui.MainActivity t269 f} in proc activity list not using proc ProcessRecord{be5e662 3858:org.sufficientlysecure.keychain.debug/u0a180}?!? Using null instead.
> .
> .
> Force stopping org.sufficientlysecure.keychain.debug appid=10180 user=0: pkg changed

After this the service is restarted automatically. Since it's a service crash nothing really happens as far as the user is concerned.

**Comment by adithyaphilip** [comment]
I'm afraid the service crashing isn't really acceptable. Can you find a way to fix it?

**Comment by advaita13** [comment]
Yes, no crash is acceptable. Trying to figure out the root cause, a bit difficult since I had to make quite a few changes in order to implement this feature. Only a matter of time now :)

**Comment by advaita13** [comment]
Alright. I've got to the bottom of it. The app crashes whenever I try to change the state of the receiver using setComponentEnabledSetting of the PackageManager, basically whenever a change is made to the package the ActivityManager kills the process. The fix was as simple as passing a DONT_KILL_APP flag with it.

`pm.setComponentEnabledSetting(compName,
                    PackageManager.COMPONENT_ENABLED_STATE_ENABLED, PackageManager.DONT_KILL_APP);`

With that, I'm happy to say that the problem is solved. I'll go ahead with a pull request?

**Comment by adithyaphilip** [comment]
Great, go ahead and make a PR. We can discuss code level changes there.

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/pull/1785
