### ISSUE TITLE
Change password when key is stripped

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1692]
Implement functionality to change the password even when the key is stripped.

**Comment by Valodim** [comment]
It is notable that to implement this feature, the partially implemented notation data for pin and other passphrase types should be removed. these parts are obsolete at this point due to #1541

**Comment by gabm** [comment]
ok guys, i have made some changes here:

https://github.com/gabm/open-keychain/tree/PasswordChangeBugfix

I had to disable some tests because they were not compiling, so please dont get confused by that.
Further there is now a new changeKeyUnlock() method in PGPKeyOperation which by now is called by the "old" modifySecretKeyRing. I dont like this because its like a "hack", so if you know how to call it directly from the menu-button press - please tell me...

I tried to use as much of the old code as possible with changing as least as possible because there are some operations and if's whose meaning I dont understand - please read carefully through the proposal and comment..
By now, i did not remove the notation data handling, but that is a very small thing to do.

Please give me some hints on how to proceed...

**Comment by dschuermann** [comment]
First, please make a pull request with "WIP" in it's title to mark it as "work in progress". We can then better discuss your changes and related issues.
Regarding the disabled tests: Which SDK + version are you using?

**Comment by Valodim** [comment]
Better use a new operation class for this, i.e., define a new operation in KeychainService complete with new parcels for input and result.

**Comment by dschuermann** [comment]
@gabm Any updates?

**Comment by AlexFJW** [comment]
I'll give this a try.

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/pull/1784
