### ISSUE TITLE
Still links to contacts even after disabling it

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1712]
Disabling "Link keys to contacts" inside the preferences and maybe also disabling the "Contact" sync inside Android's account preferences should remove all existing raw contacts created by OpenKeychain.

Users expect that OpenKeychain no longer shows up in their contacts after disabling the feature, which is right in my opinion.

@adithyaphilip Do you have some free time to look into this?

**Comment by rohands** [comment]
If @adithyaphilip is okay with it, can I work on this issue?

**Comment by adithyaphilip** [comment]
@rohands sorry, was a quick fix. If you're interested in contributing, do you think https://github.com/open-keychain/open-keychain/issues/1646 or https://github.com/open-keychain/open-keychain/issues/1644 would work for you?
@dschuermann Yup, fixed with https://github.com/open-keychain/open-keychain/pull/1713.
