### ISSUE TITLE
selectively import subkeyes

### ISSUE THREAD

**Issue by raimundomartins** [open-keychain/open-keychain#1725]
This is kind of a merge between issues #1555 and #1627. Since my master key is Ed25519, I can't import my subkey for encryption, which is rsa4096 and the only one I need to use.

It could also be another problem (if you say Openkeychain can import Ed25519), but I only get "No valid keys found in file/clipboard" with no details. I can import/export the same key in gpg2. Tried binary and ascii formats.

Also, forcing users to transport main key to mobile is bad policy, imho.

**Comment by Valodim** [comment]
OpenKeychain does not support ed25519 keys at this point. Since we can't import the primary key, we can't check subkey binding certificates. If we can't check subkey binding certificates, we don't know that a subkey belongs to a primary key. If we don't know that, we can't import the subkeys. 

Interoperability issues like this are precisely why ed25519 keys are specifically advertised as experimental.

About "forcing users to transport main key": we only need the public key, you can always export the primary key without its secret part. I agree though that the error message is quite unhelpful, we should work on that.

There is no way to work around this without implementing ed25519 -> closing this issue. Feel free to ask for clarification or reopen if I misunderstood something.

**Comment by raimundomartins** [comment]
So, you're saying that (if I had e.g. a rsa master key) I should first import my public master key, then the private subkeys?

When I created the key I thought it would only be used to handle subkeys and signing other keys. Wasn't aware that it was need for import of subkeys. Makes sense though.
I would appreciate the nice work, but I can't use it yet. I can still thank you for a quick and helpful answear, though! :)

**Comment by Valodim** [comment]
The primary key *can* be used to only handle subkeys. What that means is that it creates certificates which say "this subkey may be used for signing/encryption on my behalf". But if we aren't able to verify these certificates because we don't support the primry key's algorithm, that mechanism doesn't work.

You can export keys with gnupg in a way that the secret part is only available for some subkeys using the `--export-secret-subkeys` command. You can also use the "strip subkey" operation in OpenKeychain (Key View -> Advanced -> Subkeys -> Edit) to strip the secret part of specific subkeys after import.

**Comment by raimundomartins** [comment]
Poor phrasing on my end. When I said "only handle subkeys" I meant in the offline machine, i.e. always gpg, so no incompatibility. The verification needing primary key was the part that made sense, and I should have foreseed it, but didn't.

Yes, I'm aware of the gpg command, and assumed (from other issues) I could do that on openkeychain.

Thank you!
