### ISSUE TITLE
Signature shown wrongly as invalid

### ISSUE THREAD

**Issue by ukoehler** [open-keychain/open-keychain#1787]
Send myself a signed and a signed/encrypted email with
K-9 Mail 5.008
OpenKeychain 3.9,2
and looking at the send and received emails with OpenKeychain they are always shown as "Invalid signature", while I can decrypt ok. Looking at the email using KMail on Linux, the signature is shown as valid in all cases.

**Comment by Valodim** [comment]
can you send a signed and/or encrypted mail to me which has this problem? that would be tremendously helpful :+1: (look@my.amazin.horse)

**Comment by ukoehler** [comment]
Emails send with OpenKeychain 3.9.4 Problem still exists

**Comment by Valodim** [comment]
Got the mails. The issue here is that your key is DSA 1024 bit, which is considered insecure. This is also correctly returned by the API. I didn't check but I assume k9 stable doesn't have support to display this state, so it will show up as the next best approximation - which is an invalid signature.

In the k9 alpha, it shows up as "Insecure".

If other e-mail programs display this signature as valid and secure, they are lying and the developers should re-evaluate their cryptographic standards.

**Comment by Valodim** [comment]
Come to think of it, we don't display insecure keys as insecure in the view key activity. We should really do that... ping @dschuermann

**Comment by ukoehler** [comment]
Many thanks for the help. Will look into that. One more question: When signing with KMail I have to switch to deprecated inline mode. Is RFC 3156: MIME Security with OpenPGP going to be handled in the future. I cannot verify those signatures at all or is that the same DSA 1024 bit problem.

**Comment by Valodim** [comment]
This is being worked on, and a first technically working version is included in the K9 Alpha. Check out the [k9 alpha channel](https://github.com/k9mail/k-9/wiki/AlphaTester) if you want those features and maybe help with testing :+1:

**Comment by dschuermann** [comment]
@Valodim Insecure status is tracked here: https://github.com/open-keychain/open-keychain/issues/1476
