### ISSUE TITLE
App broken

### ISSUE THREAD

**Issue by emelsk** [open-keychain/open-keychain#1788]
Today's update broke the app entirely :-/

**Comment by markusj** [comment]
To add a few bits of information:
OKC dies because of a SQLiteException. index keys_by_rank already exists (code 1) while compiling CREATE INDEX keys_by_rank ON keys (rank); at KeychainDatabase.onUpgrade(), line 307.

**Comment by Valodim** [comment]
wow, wtf. on it.

**Comment by Valodim** [comment]
Fixed it. This was caused by a bug introduced in d6e4936fa54dc3577296dbadaeb556178dcad2c3 (over a year ago), which ridiculously only now started to have an effect from the completely harmless looking other commit b4ea59bf7cfec8f505622dd80903d2f8a4461570. Fix is on the way to the play store, all data should hopefully be preserved. Sorry about that.

**Comment by emelsk** [comment]
Perfect, it works again. Thank you!
