### ISSUE TITLE
Wrong "Invalid signature"

### ISSUE THREAD

**Issue by mouse07410** [open-keychain/open-keychain#1790]
When I send cleartext-signed message to peers that do not use PGP in their replies, OpenKeychain refuses to display their response, and just give me the red bar with "Invalid signature" in it.

The problem of course is that there is no signature in the response besides what's in the **quoted** message. This is what it looks like in Apple Mail:
![openkeychain-mess](https://cloud.githubusercontent.com/assets/5923577/13801219/4ac77f18-eb06-11e5-9f25-64b00d449e19.png)

Trying to cut-and-paste from that window though produced this:
```
......
 Do we need to discuss confidential things???

On Mar 14, 2016, at 4:58 PM, Uri ... wrote:

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

......
Thanks!
Uri
- --
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-----BEGIN PGP SIGNATURE-----

iQFABAEBCgAqIxxVcmkgQmx1bWVudGhhbCAoTUlUKSA8dXJpQG1pdC5lZHU+BQJW
5yX2AAoJEGw0pJdB6QkCz4MH/3nEa2AgrHtdcWjC5MVa6Ut6f0O8nLXpBX05Xikh
GpGSbNuzV+Q3VNQIBgAsvABQgeLyzd04sf/L6EtRhYpFgFX2CDJZY61yTqst51yq
ZoB9j+dHi9zbFRnLcvDJUSX59q6RrXxn6te/hdyXiulL7oDSgqcZkEmA6eidt8Bb
AhVyRcgJrfRiIuBAwLKpOqTRCV4MKpb7ifKHQGVNY9cA/AQKAMmAQfkxtAcZc0QN
uCaaYaZI+Cf8egJ7G5k6kPRj2M80nsdJC4BlU1+MDaKWKBxUX9sMTCVpqpok6oHI
FArZCs2MFHTkrU9BrWQ0B7YVM91g67ncrKOYlOHbKe9/o3A=
=eKhJ
-----END PGP SIGNATURE-----
```

On their end - it looks like Microsoft Exchange is involved, possibly MS Outlook. Server - Gmail. On my end - OpenKeychain-3.9.4 (was 3.9.2) and K-9 Mail 5.008 (released).

I can see how OpenKeychain can get confused, if the quoted message is simply appended to the response. But it is rather inappropriate to prevent the incoming message from being viewed! Putting that very visible red bar with "Invalid signature" should be quite enough to inform the reader/receiver that there are problems with message signature. Completely preventing me from even seeing this message on my mobile device is bad. **I urge you to reconsider**. 

**Update** R2Mail2 app displays the message in question correctly. And it correctly determines that the signature in the appended message does not relate to the current one. So it reports the message as not signed (which is correct). *The main reason I don't switch to R2Mail2 is that it does not support hardware tokens.*

**Comment by Valodim** [comment]
That only the signed part is shown is a known bug in current k9. OpenKeychain is only used in an api call to verify the signature, what parts of it are displayed in what way is not up to us. This is fixed in current k9 master, but there are no plans to backport the fix.

That the signature is invalid seems to be a different issue. The text you pasted doesn't check out for me as valid in either openkeychain nor gpg, did you scrub it with those `.....` or is that a test message?

**Comment by mouse07410** [comment]
> That only the signed part is shown is a known bug in current k9......This is fixed in current k9 master, but there are no plans to backport the fix.

I see. The implication is that as soon as the new K-9 update is released - it should include this fix, correct?

> That the signature is invalid seems to be a different issue.

That signature cannot be valid because the text it surrounds has been reformatted by the reply (and presumably by MS Outlook) even before I posted it here.

> The text you pasted doesn't check out for me as valid in either openkeychain nor gpg, did you scrub it with those ..... or is that a test message?

Yes and yes. I've posted it simply to illustrate the situation. 

What I saw (see) as a problem is not that an attempt to verify it fails (there can be all kinds of prefixes in those lines - from blanks and tabs to ">").

My problems are: (a) the fact that it confused the signature on the **appended** message with the signature for the entire response, and (b) the fact that the actual (unsigned) response is not displayed.

If I understood you correctly, the (b) part will go away as soon as the next K-9 update hits the Play store. I wonder whether you can do anything about (a), especially since R2Mail2 doesn't seem to have a problem telling a signature that applies to this message from a signature that happened to be a part of the message quoted in this one.

**Comment by Valodim** [comment]
both (a) and (b) are k9 issues, we do not do any email parsing on our side (at this point).

The "as soon as k9 update" thought is correct, however it will be a couple of months until that happens because k9 has been in sort of an intermediate state for a long time now and will need some time until it's back to anything "stable". If you're feeling experimental, there will be an alpha of k9 in the play store in a couple of days which includes a year's worth of progress including this, and needs all the testers it can get :+1:

**Comment by mouse07410** [comment]
Understand, thank you!
