### ISSUE TITLE
Security Token: Improvements to USB support

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1833]
- Add more devices to the whitelist: e.g., Nitrokey
- Other pictures with USB devices for the dialog
- Key generation on security token: a method is already there but not used because key generation over NFC is extremely unreliable and works only 1/3 of the time. I suspect that is because of power issues, which should not happen with USB.
- warning for reset procedure?
- animation when going from the CreateSecurityTokenWaitFragment moves into the wrong direction (just a minor glitch)

**Comment by dschuermann** [comment]
Nitrokey support work is here: https://github.com/open-keychain/open-keychain/pull/1834

**Comment by nmikhailov** [comment]
@dschuermann Could you provide some feedback/your thoughts regarding token reset issue?

**Comment by dschuermann** [comment]
Regarding reset: I tried with an unlocked YubiKey which has been flashed with 1.0.10 and it always worked. Maybe the other YubiKey I bricked was really flashed with a buggy version. Unfortunately, I wasn't able to get the applet version from the other YubiKey.
Maybe we should still add a warning here.

Regarding dialog design/images: During the reset procedure no progress animation has been shown. In all other cases this worked, but we obviously need other pictures instead of the NFC-related ones. Due the usage of a widget from the nordpol library, I first thought that we need to integrate these USB images there, but maybe we should simply patch nordpol to have setters to select different images from OpenKeychain. Not sure if this is something you want to work on, if not, please tell me and I will try to get something done.

**Comment by nmikhailov** [comment]
Yes, it will be better if you will take care of images and animations. I won't be able to produce nice graphics anyway.

Although these were my ideas regarding animation update:
1. First step: add otg cable on the right side of the image.
2. When user connects device animate nfc token or otg cable depending on the transport type and fade away another.

**Comment by nmikhailov** [comment]
> Key generation on security token: a method is already there but not used because key generation over NFC is extremely unreliable and works only 1/3 of the time. I suspect that is because of power issues, which should not happen with USB.

Did some tests:

- Couldn't generate keys via NFC (Nexus 5X) 4 times out of 4, connection terminates, error 'Security Token has been taken off too early...' is displayed.
- Generating keys via USB worked 3 times out of 3.

**Comment by dschuermann** [comment]
great, we should then switch to generating keys on the token itself when USB is used.

**Comment by norani** [comment]
I plan to use my own USB device(a token with fingerprint authentication) instead of Yubikey. I store pgp certificate into hidden area of USB, then connect my USB with my phone using OTG cable. Then OpenKeyChain will detect the key that match with the email that I sign in. OpenKeyChain will make it as a default key to be used in K9-Mail. Does this plan are possible to be developed?

**Comment by dschuermann** [comment]
@norani Your token needs to support the [OpenPGP card standard](http://g10code.com/p-card.html), everything else will not be supported.

**Comment by norani** [comment]
So I need to implement the support for my token's card in GnuPG? But the software is not an open source. Thus,I have to use OpenPGP card on my token OR provide specification to my token's card by my own OR buy the card? Sorry, I'm new to OpenPgP environment

**Comment by dschuermann** [comment]
@norani I said nothing about GnuPG :P Your token needs to support the OpenPGP card standard I linked to.

**Comment by norani** [comment]
I don't understand what is OpenPGP card standard. Based on the link you gave, OpenPGP card is integrated with GnuPG functions. So, you mean standard is specification/features of the card?(eg:3 independent 2048 bit RSA keys (signing,encryption,authentication), Key lengths reducable to 1024 bit; key length of signature keys increasable to 3072 bit. , etc)

**Comment by Valodim** [comment]
If your usb device doesn't say it supports the openpgp card standard, it is not compatible.

**Comment by dschuermann** [comment]
We just released 3.9.5 which includes the support by @nmikhailov for security tokens over USB. I haven't announced it in the changelog since I consider it "experimental". We will announce it in th enext major version, but for all reading this: You can now test the feature using the latest stable from Google Play or F-Droid.

**Comment by dschuermann** [comment]
I fixed the animation in https://github.com/open-keychain/open-keychain/commit/d72001c6907ff50890673cd91b266c34c73ec84b

**Comment by nmikhailov** [comment]
There is a demand for gnuk support [IRC logs](https://gist.github.com/nmikhailov/5442672cb53f85f04f6ffb7d7d14a2c6)

**Comment by mrvdb** [comment]
Should this theoretically also work for the app running on chromeos? (Asus C100PA) Tried it with a yubikey neo 3.3.0 but it does not seem to work. (app version  4.1 beta3 (41002))

**Comment by dschuermann** [comment]
@mrvdb How did you install OpenKeychain on Chrome OS? Currently we have no plans to support Chrome OS by default, see https://github.com/open-keychain/open-keychain/issues/1704

**Comment by mrvdb** [comment]
@dschuermann since last week there are 3 devices which have received an update which includes the google playstore  app to install android apps. The Asus C100PA is one of them. In time, many chromebooks will be capable of running native android apps. 
Admitted, it's still early days, but the app works like a charm and it was the missing link for me to have an all yubikey based setup.

**Comment by nmikhailov** [comment]
@mrvdb It seems that ARC(android runtime for chrome) doesn't support USB access. So yubikey won't work unless they will add it.
http://stackoverflow.com/questions/29509692/arc-with-usb-access

**Comment by s72785** [comment]
"Whitelist" does refer to [USB device filter][https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/res/xml/usb_device_filter.xml] ?

**Comment by nmikhailov** [comment]
@s72785 yes. Which device do you have?

**Comment by s72785** [comment]
Just curious which to buy - namely an alternative to yubikey as they went proprietary. Looks like Nitrokey Pro is the next best to go for.

**Comment by nmikhailov** [comment]
@s72785 note that there is also an option for [NFC-enabled card](https://www.openkeychain.org/faq/#nfc-security-tokens)s

**Comment by aryoda** [comment]
I have just **successfully tested** my **Nitrokey Pro** stick with

- a **OnePlus 3T** mobile phone (https://oneplus.net)
- using the original USB OTG adapter cable of OnePlus
- running **LineageOS14.1**-20170222-NIGHTLY-oneplus3 (Android 7.1.1)
- K-9 Mail 5.203
- OpenKeychain 4.2.4.
- with K9 and OpenKeychain installed via the f-droid app

I can decrypt emails received with the K-9 email client.

The key problem to solve was to export the "secret key" (that contains only a reference to the Nitrokey but
does **not** contain the private key) from a desktop computer where I have already installed
the NitrokeyPlus and import that "secret key" file after plugging the Nitrokey Plus into the mobile phone.
Use "Manage my keys > Use security token > Import key file" to do this once.

A port of the Nitrokey App to Android is therefore not required (as indicated in the wiki https://github.com/Nitrokey/wiki/wiki/Ideas#port-nitrokey-app-to-android:
"OpenKeychain is an GPG-like Android app which works with Yubikey NFC already. It should be relatively easy to extend it to work with the Nitrokey via USB.").

**Comment by Valodim** [comment]
This should also work by importing the public key but yes, unfortunately the key can't completely be constructed from the info available from the Nitrokey. The UI could be much better at reflecting that, see #1587 for some earlier thoughts and mockups on this.

**Comment by uvok** [comment]
Hi, I thought this issue is related, so I'll write in here.

I'm having some issues with setting up my Yubikey. The screen "Would you like to use this blank security token..." appears, either when I insert the Yubikey via an USB OTG cable, or when navigate to Manage my keys -> Use security token. (When I insert the YubiKey when the homescreen is shown, the screen flickers shortly, but nothing else hapens)

The page says "You will be prompted when it is needed again", but when I click next on the page where I choose my PIN, and the YubiKey is not connected, OpenKeyChain crashes

```
03-01 11:02:15.962 21967 21967 E AndroidRuntime: FATAL EXCEPTION: main
03-01 11:02:15.962 21967 21967 E AndroidRuntime: Process: org.sufficientlysecure.keychain, PID: 21967
03-01 11:02:15.962 21967 21967 E AndroidRuntime: Theme: themes:{default=overlay:org.cyanogenmod.hexolibre, iconPack:org.cyanogenmod.hexolibre, fontPkg:org.cyanogenmod.hexolibre, com.android.systemui=overlay:org.cyanogenmod.hexolibre, com.android.systemui.navbar=overlay:org.cyanogenmod.hexolibre}
03-01 11:02:15.962 21967 21967 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from null array
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at org.sufficientlysecure.keychain.securitytoken.SecurityTokenHelper.parseOpenPgpVersion(SecurityTokenHelper.java:107)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at org.sufficientlysecure.keychain.ui.CreateSecurityTokenPinFragment.nextClicked(CreateSecurityTokenPinFragment.java:204)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at org.sufficientlysecure.keychain.ui.CreateSecurityTokenPinFragment.access$100(CreateSecurityTokenPinFragment.java:41)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at org.sufficientlysecure.keychain.ui.CreateSecurityTokenPinFragment$3.onClick(CreateSecurityTokenPinFragment.java:163)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at android.view.View.performClick(View.java:5204)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:21158)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-01 11:02:15.969  1527  3169 W ActivityManager:   Force finishing activity org.sufficientlysecure.keychain/.ui.CreateKeyActivity
```

When I attach my YubiKey on the PIN screen, unfortunately the first page appears again, since I set OpenKeyChain as default application for this USB device. I can go back, though. The Admin Key changed then. The Pin fields still show dots.

When I click Next now, I get the "You entered the following identity" screen.
When I click "Create Key", the key is created, but then I get "Entered PIN is too short. PINs are at least 6 digits long. Error Invalid data"

Unfortunately, I can't enter any PIN while the YubiKey is connected.

Maybe related to #1937 ?

Asus Zenfone 2
CyanogenMod 13.0
OpenKeyChain 4.2.4
YubiKey Firmware Version 4.3.4

**Comment by dschuermann** [comment]
@uvok Thanks for your report. Better create a new issue, this one is getting muddled. Please also include the information what YubiKey you are using: https://www.yubico.com/products/yubikey-hardware/

**Comment by techge** [comment]
> Update: It seems there is still an open issue: If I try to compose an encrypted email I have to sign it too (K9 cannot encrypt without signing it seems, see the doc https://k9mail.github.io/documentation/security/pgpmime_current.html). To sign it asks for a password (which seems to be the passphrase, NOT the Nitrokey Pro / USB hardware token PIN). I will investigate that and post an issue if I can make this reproducible...

I can confirm @aryoda comment to signing Mails.

But the problem with asking for a passphrase seems to be that it tries to use a different key at all. I realized it because it was asking for the passphrase of a slightly differently named key in my keychain.
To affirm this I deleted all keys in my chain. Then only imported the keys from the Nitrokey Pro (which works fine for decryption in K9Mail). When composing a mail I got a NotFoundException.

It has maybe something to do with the fact that the key for signing is a different key than for encryption?

Please tell me if I shall open a new issue.

**Comment by Valodim** [comment]
For reference, K-9 can't encrypt without signing because that's a misfeature. Check out my [blog post](https://k9mail.github.io/2017/01/30/OpenPGP-Considerations-Part-II.html) on this.

OpenKeychain should use the key that is specified in K-9 as the account's associated key, if it uses a different one that's a serious bug. It's possible that subkeys are treated differently!

@techge Can you go to Advanced -> Subkeys for the nitrokey, and list the keys as shown there (or alternatively make a screenshot)? just to make sure everything is alright there.

**Comment by techge** [comment]
@Valodim After reading your post I looked at K9 crypto settings to look whether I am able to choose special subkeys for signing. Well I can not, but after rechoosing the key for this account, the sending works fine.

So for me the problem was that K9 realized automatically which key to choose for decryption but not automatically detected that the prior key got deleted and that I may want to use a different key for signing now. Explicitly choosing the new imported key in K9 fixed the problem. Sorry for the noise.

@aryoda could you please have a look if you still experience the problems you described and if my solution works for you as well?

**Comment by techge** [comment]
I'd like to add another thing to the post of @aryoda 
> The key problem to solve was to export the "secret key" (that contains only a reference to the Nitrokey but does not contain the private key) from a desktop computer where I have already installed
the NitrokeyPlus and to import that "secret key" file after plugging the Nitrokey Plus into the mobile phone.

This may was needed in the past, but it is not anymore (using OpenKeychain 4.5). It is enough to have the public key at hand (but this is the needed for desktop keychains as well). If you have given a URL on the card you can easily fetch the public key from their within OpenKeychain. Nothing else needed. 

Works like a charm! Thank you all!

**Comment by aryoda** [comment]
@techge Thanks for sticking to my problem(s) and helping me to recognize how stupid I was ;-)

I have done a complete re-installation of LineageOS + OpenKeyChain + K9 Mail on my OnePlus 3T rule out any unwanted modification from my earlier configuration and installation trials. Testing environment:

- Mobile: OnePlus 3T
- LineageOS 14.1.20170908 (Android 7.1.2)
- K-9 Mail 5.208
- OpenKeychain 4.6

**Finally I have solved all problems** and explain the reason and how diagnose it here.

**Reason**

OpenKeychain will recognize the Nitrokey (or every other supported smart card) and work correctly if you have put not only the private encryption (sub) key **but also the signature sub key** on the Nitrokey.

You then only connect the Nitrokey for the first time with your mobile running OpenKeychain and follow the installation steps on the screen. You only need to install the public key from a key server or a file since the Nitrokey (like all other smartcards?) does not store the public key.

Don't forget to assign this key in K9 Mail as your identity in the menu (account settings > Cryptography)

Now I can use K9 Mail to

- decrypt
- sign
- encrypt (with automatic signing which is enforce by K9 Mail)


**Diagnosis**

To check your Nitrokey or smart card for the existence of the required signature sub key open a command shell and use the gpg tools (the Nitrokey must be connected):

```
gpg --card-status
```

A missing signature sub key looks like this in the output:

```
Signature key ....: [none]
Encryption key....: FFEE AABB 0001 CCDD ...
      created ....: 2017-01-01 10:04:22
Authentication key: [none]
```

You then have to create a new signature sub key or move an existing one onto the Nitrokey (there are many step-by-step instructions for that, e. g see: https://www.gnupg.org/howtos/card-howto/en/smartcard-howto-single.html#id2507414).

The output for an existing signature sub key looks like this:

```
Signature key ....: A0FE 12BB 3F9A D1F9 ...
      created ....: 2017-01-01 10:04:22
Encryption key....: FFEE AABB 0001 CCDD ...
      created ....: 2017-01-01 10:04:22
Authentication key: [none]
```

**Comment by Valodim** [comment]
This flow will hopefully improve even further with #2157. unfortunately creating a key on the nitro still fails for me, and looking at the relevant code I have no clue what could be causing this. I hope @nmikhailov can have a look at this at some point, until then we might want to disable key generation with devices that aren't known to work.

**Comment by dschuermann** [comment]
Most of this has been done in https://github.com/open-keychain/open-keychain/pull/2157
