### ISSUE TITLE
Make ACTION_GET_KEY find _sub_keys as well.

### ISSUE THREAD

**Issue by mgeier63** [open-keychain/open-keychain#1841]
I have a use case where, upon receiving an encrypted message,  I would like  to show to the user the list of _other_ recipients , i.e. a list of all the public keys the message has been encrypted for.
And I'd like to show not only the key ID but also the identity information (email address) of that key  (in case the user has that key stored in his local keyring )

Now one can using ACTION_GET_KEY to retrieve public keys from the keyring and that works fine for main keys, but unfortunately this operation only finds _main_ keys with a matching key ID - though in most cases the keys used for encryption are _sub_ keys.

Would it be possible to add support for retrieving _sub_ keys by their key ID?

[I could probably create a pull request for this, but It would either  change the general behavior of ACTION_GET_KEY  or add a boolean extra flag to that action or even create another action like ACTION_GET_SUBKEY or so. 
Since this is touching the API design / contract either way, I'd rather leave this decision to the "core" people...]

**Comment by dschuermann** [comment]
Hmmm, I not convinced.

The API has been designed to work with whole OpenPGP keys and thus the key IDs of the main keys and not individual subkeys, because I think that client developers shouldn't have to deal with these.
Can you explain more about the use case?
* In general, I don't see any valid scenario where it makes sense to display Key IDs, but that's a longer discussion (part of the reasons are here: https://github.com/open-keychain/open-keychain/wiki/OpenPGP-Security#key-ids-arent-displayed)
* Why does the user need to know the exact subkey, which has been used?

**Comment by mgeier63** [comment]
The user shall be able to reply to one or all parties a pgp message has been encoded to.
Think about a pgp email but without the FROM/CC email headers - all my client knows, after receiving a pgp message and parsing it, are the (sub) key IDs of the public keys the message has been encrypted for.

If the user doesn't have those keys in his keychain, I'm offering him to download them.
But if he does have them, I want to show him the identity information of those keys before he replies.

So I agree, there is no need to show the key IDs to the user (currently I do but i will replace this by "unknown key, download?")

What I'm doing right now is to (try to) get the whole key via ACTION_GET_KEY, parse it and extract the identity information (as I said initially, this doesn't work if the key used for encryption is a subkey) .

So some additional API that returns identity information only (and works with subkey IDs) would probably be a better solution!?

**Comment by dschuermann** [comment]
@Valodim can you comment on this issue? I think these ideas are also related to your usage and plans with the API for K-9 Mail.

**Comment by Valodim** [comment]
I see no problem changing ACTION_GET_KEY to search on subkey id rather than master key id. The namespace is unambiguous, and if the client app knows a subkey id I see no reason not to provide the information which key it belongs to (and subsequently information about that key).

that said, retrieving keys to parse them and show information about them that way sounds like a bad idea. if (reasonable) information about a key is needed, it should be provided by the api

**Comment by dschuermann** [comment]
Good point @Valodim 

@mgeier63 thus, we would accept a pull request to add this behaviour to the existing ACTION_GET_KEY. I don't think we should introduce a new extra, just use the existing API design and also search by subkey ID.

**Comment by Valodim** [comment]
this is a trivial fix. done in 4c063ebe4683c0ffd0a80ff617967e8134b484fa, if someone could test it to make sure it works as intended that'd be swell

**Comment by mgeier63** [comment]
sorry, was away for a couple of days...

Have now tested it and can confirm it works as intended!
thanks!
