### ISSUE TITLE
Changing keylength is not straightforward

### ISSUE THREAD

**Issue by nmikhailov** [open-keychain/open-keychain#1906]
Branching from #1896 .

It is not obvious how to change keylength on key creation. From google play store comments:

> Key size version 3.9.5; installed on tablet (android 5)- when creating a key; doesn't give option to chose the key size 1028 to 4096 bits!!!!! Why? I hope it's not because the default key size that is forced by the gov. is only 1028 bits (crackable).

Also this is frequently discussend on IRC, and

> (22:16:04) nmikhailov1: JohnDroid: when you are creating a key press on button in title bar
> (22:16:50) nmikhailov1: JohnDroid: its on a screen after configuring password
> (22:17:40) JohnDroid: or I could just use APG app and generate a 4096 key from there
> (22:19:03) nmikhailov1: JohnDroid: yes, but generating 4096 key in openkeychain is possible
> (22:19:24) JohnDroid: nmikhailov1: yes but its not straithforward

cc @dschuermann

**Comment by dschuermann** [comment]
So my opinion on this is that the user should not decide about the key type, size, algorithm, configuration etc.
No one complains about the other parameters except the key size because it's a sensible topic, which people *think* they understand.
Still, current research and standards suggest that 3072 bit RSA is big enough for the next years (https://www.keylength.com), that's why we use this as the default.
If 3072 bit RSA is no longer secure in 15 years, I hope we will have already switched to ECC by default.

There is no visible UI for crypto choices in Firefox, Chrome, IE, Signal, Threema or any other modern application, still people want the coice in PGP apps. IMHO this is a cultural issue of long-term PGP users, not the "right" thing to do.

If we make the expert options more visible, people will click on it and change the defaults, and then write a long blog post about it how to be more "secure".
This happens with gpg (there are thousands of gpg tutorials online with crazy weird key configs). I think this culture is one of the key issues why people tend to think PGP is difficult.

Still, if there is a concrete proposal how to change the current key generation screen, I am open to discuss.

**Comment by nmikhailov** [comment]
I think that significant part of our specific userbase cares about keylength very much.
Virtually this means that they usually want the biggest ones. Whenever this is an issue or not is a debatable topic. But this culture is already established and I don't think that working against it is way to go.

Overall I think current topbar button is hidden  too much.
I think it would be better to move it to the main area. Or maybe even add a combobox with keylength and 'adanced settings' button next to it.

**Comment by dschuermann** [comment]
Another anecdote: We had also at least the same amount of complaints about OpenKeychain displaying an icon that a signature is "insecure". This is displayed when a key is 1024 bit RSA. People complained that they used the key for a long time and don't want to switch to a longer bit size. Still I consider 1024 bit RSA no longer secure that's why it's not a valid signature for me.

**Comment by dschuermann** [comment]
We posted at the same time :grimacing: 

We already work against the culture in several areas (we don't display key IDs, use QR Codes, no mention of secret/private key, etc), IMHO this is the way to go. We still have to go a long way to get rid of all cultural problems though.

My main issue is that I don't want to expose explicit key sizes to the user (because the normal user should not be required to know what this is and means) and I don't want to add another choice to the key creation wizard. People are already mentally overloaded by all existing textfields.

**Comment by nmikhailov** [comment]
Well if that is a part of large deliberate decision it makes little sence to apply my suggestions. Can't say that I agree with your view though.

**Comment by Valodim** [comment]
"They want the biggest" is exactly right. The problem is that there is no "biggest" one - so what people then go for is what they perceive as "big" at that particular point. This leads to an "arms race" between implementations, and there are a lot of people who will argue that they *need* the bigger number there, and in the end their argument boils down to "because I saw that it's possible to have bigger numbers" with no cryptographic basis whatsoever.

GnuPG quit this long ago, [they generate 2048 bit keys](https://www.gnupg.org/faq/gnupg-faq.html#default_rsa2048), so we are already pushing this with a 3072 default. If we really wanted to improve in this area, the way to go is certainly ECC (but we better not tell people that ecc 256 is equivalent to 16k RSA, or we will have even more people demanding those :hurtrealbad:)

**Comment by nmikhailov** [comment]
> Oh, and we certainly shouldn't base cryptographic decisions on play store reviews like the first one. :P

That was never proposed, this issue is purely about UX and accesibility, not about chainging crypto or defaults.

**Comment by juanito003** [comment]
I suggest we don't just rely on NIST predictions and go for 4096 bit RSA as default or ECC.
If we have stronger crypto why can't we just use it?
Does someone know about Jericho Comms? Another interesting point of view.

> Also the standards themselves [being deliberately weakened](http://www.nytimes.com/interactive/2013/09/05/us/documents-reveal-nsa-campaign-against-encryption.html?ref=us) by the NSA. Also that the [NSA are years ahead in cryptanalysis](http://arstechnica.com/security/2012/06/flame-crypto-breakthrough/).

[...]

> Most companies and organisations worldwide are using Suite B Cryptography algorithms which have been publically published by the NIST for security of unclassified, non-military government networks. This has led most other governments, companies and individuals worldwide to adopt these standards thinking that if they are secure for the government then they must be secure for them too. In this NSA leak we see privileged, top secret information that the NSA's real plan has actually been to covertly influence these encryption policies, designs, standards and specifications to make them amenable to advanced cryptanalytic capabilities of the NSA and exploitable through their signals intelligence collection network with prior knowledge of the modification. The aim being that everyone in the world believes their systems' are secure, but in reality, and only known to the NSA, their systems are exploitable. A lot of software projects and companies still do not understand this and continue to use standards from the NIST. This gives them and their users a false sense of security that their systems are secure from the NSA. 

Source: https://joshua-m-david.github.io/jerichoencryption/

**Comment by dschuermann** [comment]
@nmikhailov What if we create something like a "Advanced" expand button (with these down or up arrows as in https://github.com/open-keychain/open-keychain/pull/1885#issuecomment-237811572) in the last step of the wizard and if clicked show exactly the same new drop down there as in the key edit screen (see https://github.com/open-keychain/open-keychain/pull/1796#issuecomment-204435965) ?

**Comment by kehugter** [comment]
> I think that significant part of our specific userbase cares about keylength very much.

Yes, only about keylength, not about ~~cryptonerd~~ security. You can generate a 16k key but your master key is still on your phone, which is prone to get lost, is almost always online and is in most cases remote-controlled by GAPPS.

I think the wizard has everything it needs to be useful. If you really want to add the advanced wizard, I'd suggest that you hide it in the settings, not in the wizard.

**Comment by jinformatique** [comment]
Maybe most case use GAPPS, but not me. I use latest cyanogenmod without GAPPS. And I use a yubikey, so the key is not stored in my phone. 

What do you suggest if a generate a 16k key, where do I store the private key? On my laptop using full disk encryption? 

And by the way, the best use case scenario for using GPG key would be to generate it on a desktop without any internet connection. And then generated subkeys used to encrypt and decrypt. So the master key would be stored on a encrypted usb key only offline.

**Comment by dschuermann** [comment]
@Valodim said
> so what people then go for is what they perceive as "big" at that particular point.

@jinformatique 
> If we have stronger crypto why can't we just use it?

Do you even realize what you just did? You proofed @Valodim 's point. What's the limit here? As @kehugter said (with irony), why not generate 16k keys? Why do you think 4096 bit keys or 16k bit keys are more protected from the NSA? Jericho Encryption is no valid source, I want to see a crypto paper or a paper by a standardization organization that says 3072 is not enough. NIST is not the only source we rely on, feel free to consult https://www.keylength.com/

If you think that you need more protection than other people, feel free to to use a YubiKey and your own Android rom without gapps. It's totally understandable to do so. This is important, instead of longer key sizes, which don't give you any advantage.

Going back to the discussion about UX: What do you think of my proposal @kehugter @nmikhailov . Optionally, we could also go the route by adding it to the Experimental Features, I would also be okay with this, but I predict that this will not stop the people from asking on IRC.

**Comment by nmikhailov** [comment]
@dschuermann  I think that this will be definetly more visible than actionbar button. Although this makes the wizzard flow a little bit weird, don't you think? We can postprone this untill somebody will come up with better solution. 

I also don't get why there is so much offtopic discussion about key lengths. This issue was not meat to advertise bigger/lesser keylengths, its about possible improvements to the UX to makes some users less confused.

**Comment by dschuermann** [comment]
@nmikhailov The offtopic discussion about key length comes from the Google Play comment you posted and because making a choice visible encourages people to select something which is not the default. This again results in tutorials where bigger key length are proposed instead of using the default one. Then at one point people think 3072 is not enough...
Sry I started rambling again :grimacing:

**Comment by kehugter** [comment]
I think that an option to toggle advanced features in the wizard itself will lead to more people peeking and using it. If you really don't want to promote it, it shouldn't be in the users way.

> I predict that this will not stop the people from asking on IRC.

A new entry in the advanced section of the FAQ could help mitigate IRC queries. Maybe quote Werner Koch [1]

> Such keys are at best a political statement and a good laugh for some
> NSA folks.

[1] https://lists.gnupg.org/pipermail/gnupg-users/2011-August/042708.html
