### ISSUE TITLE
Null object reference when ECDSA key

### ISSUE THREAD

**Issue by hadogenes** [open-keychain/open-keychain#1933]
I've recently generated ECDSA(brainpoolIP256r1) gpg key and applications which use OpenKeychain (k9-mail and PaswordStore) generate error:

> Attempt to invoke virtual method 'org.bouncycastle.math.ec.ECCurve org.bouncycastle.asn1.x9.X9ECParameters.getCurve()' on a null object reference

I use OpenKeychain v.4.1 from f-droid

**Comment by DominikGolle** [comment]
I have the same error.
Reimporting my key didn't help.
Are there any other solutions?
Thanks!

**Comment by doubledown187** [comment]
Same here.
A friend and I each have a brainpoolP512r1 key which we created with GPG on a Windows machine.
Enigmail and iPGMail on his iPhone can handle the keys without problem.

When I want to decrypt one of his mails I am prompted to enter the password for my private key (in K9). After that I get the error message

> Attempt to invoke virtual method 'org.bouncycastle.math.ec.ECCurve  
> org.bouncycastle.asn1.x9.X9ECParameters.getCurve()' on a null object reference

On the other hand, when I want to send an encrypted mail to him K9 finds his key in the keychain, but upon bushing the send button I get an error message saying that a signing key cannot be found.

It turns out that both keys have two subkeys - one for encryption and one for signing and authetication.

I read in another post that having three subkeys where each one is dedicated to a single purpose resolves the issue. However, we don't want to create all new keys.
Since Enigmail and iPGMail can handle the keys perfectly this should just be a minor change in how the keys are fetched from the keychain, right?

Really would appreciate if one of you had a look into this.

Thanks, and keep it up,
Steven

**Comment by Valodim** [comment]
Wow, I can't believe this issue has been open since September 2016. It came up again recently in #2261, and turned out to be a simple fix. This will fixed be in the next release. Sorry about that delay.
