### ISSUE TITLE
Not able to send encrypted mail to receipts whose keys are not present

### ISSUE THREAD

**Issue by kadaj** [open-keychain/open-keychain#1963]
When I try to send an signed, encrypted email to a recipient the openkeychain pops up says "No keys were found for these email addressess" and the mail cannot be send. There is no need for the recipient's  key inorder to send. Eg: Thunderbird (dekstop) sends fine. Please remove this restriction.

**Comment by Valodim** [comment]
This is incorrect. There is indeed a need for the recipient's key in order to send, that's the basic idea of asymmetric encryption. When you are signing and encrypting messages to someone else, you are essentially establishing a secure communication channel between your key and the recipient's. If you don't have the recipient's key, you can't do that.

I might be missing something here. If I am, please describe what you think is wrong in OpenKeychain in more detail.

**Comment by kadaj** [comment]
Correct. My bad. What happened with Thunderbird was that it first shows key is not found for recipient, but has a select recipient where I had choosen myself. So when I send it to my another mail, since the key is present, I am able to decrypt. If I don't have the public key, I won't be able to send encrypted mail to them. Thanks.
