### ISSUE TITLE
Add version underneath ---Begin pgp message---

### ISSUE THREAD

**Issue by iminderN** [open-keychain/open-keychain#2081]
How can we add this version line in the keyblock as mentioned below? Many pgp encrypters use this and would be great we can do this too.

-----BEGIN PGP MESSAGE----- 
Version: openkeychain  <-- **Add this line.**

owEBTQGy/pANAwACARsm2bqGdVliAcsdYgBUavgLVGVzdCBmb3IgU3RhY2tPdmVy
ZmxvdyCJARwEAAECAAYFAlRq+AsACgkQGybZuoZ1WWKlVgf/cfsU/aJYnNIimAwq
DKKfWox9c7rEC5ug6qcQzb5YFPsGuyMtZ1Tx9SwCmvU7IXtlnK/BY6H4ut50zOzl
8O8fYaaK63NupeEThlNK1fMvTmt56GLRSgGZ9yBOdkaC3A3SWBAsniPoj5wjBr7m
/MHnqs5Gw1Mtp8I8issZzTQXGjq4j6mAli1Vb3lBpESuF/s/uOxY8jSCV8SDH0UU
RxKoVnzqXd7mD2Dv+KE8K1PKVbVNyT+vIc+rOsRKkaW+6rSXVXie4DWkKxCP5RPe
3Ma3KMark71EwNW86IWryFm8YkP4vt31HKMwW4HUb6nhFF24IQOPle51YoiyZWUC
ejtY4Q==
=xKTQ

-----END PGP MESSAGE-----

**Comment by Valodim** [comment]
This data is never even parsed except by humans looking at the raw data, which is useful only for a minor gain in debuggability. Compared to the additional generated metadata, it's not worth it. People have gotten into legal trouble based purely on the gpg version they were using, which is why we chose to remove it.
