### ISSUE TITLE
security token ecdsa signature encoding

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#2108]
Ping @af-anssi 

A discussion just came up on irc with @biafra23 and @nmikhailov, and we were a little confused about the signature format for ECDSA.

Looking at [SecurityTokenHelper:700](https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenHelper.java#L700), OpenKeychain expects the returned data to be the raw values for R and S, and then applies ASN1 encoding. In SmartPGP's [sign method](https://github.com/ANSSI-FR/SmartPGP/blob/master/src/fr/anssi/smartpgp/PGPKey.java#L663), it looks like the asn1 value is decoded and then sent individually?

The openpgp card spec isn't very detailed on what should happen here, can you elaborate what's going on? Thanks in advance!

**Comment by nmikhailov** [comment]
This is a problem because r and s can have different lengths which breaks current assumptions in OKC.

**Comment by Valodim** [comment]
relevant code in gnupg: https://github.com/gpg/gnupg/blob/master/agent/pksign.c#L390 does assume len/2 as well, but also prepends a null byte if high bit is set for either value

**Comment by af-anssi** [comment]
The openpgp card spec does not specify anything on the format of the output of the PSO: COMPUTE DIGITAL SIGNATURE.

The format used in gnupg since 2013, as mentionned by @Valodim, is the plain format (for instance described in section 5.2 of [Elliptic Curve Cryptography from the BSI](https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TR03111/BSI-TR-03111_pdf.pdf?__blob=publicationFile). With this format, r and s are just concatenated in this order, after being padded with leading zeros if necessary to ensure r and s have the same length. In the GnuPG code cited, the prepended null byte is to avoid signing conversion problem during internal (de)serializations...

In the SmartPGP applet, r or s is padded if necessary with leading zeroes in order to ensure r and s have the same length ([PGPKey.java:702](https://github.com/ANSSI-FR/SmartPGP/blob/master/src/fr/anssi/smartpgp/PGPKey.java#L702) and [PGPKey.java:709](https://github.com/ANSSI-FR/SmartPGP/blob/master/src/fr/anssi/smartpgp/PGPKey.java#L709).

In OpenKeychain [SecurityTokenHelper.java:701](https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenHelper.java#L701), the length of the signature is checked to ensure it can be splitted exactly in two parts with the same length which correspond respectively to r and s. This is the only "correct" way to "parse" the plain format.

**Comment by Valodim** [comment]
Cool, that answers that. Thanks. I'll leave a link to this issue in the code for future reference :+1:
