### ISSUE TITLE
Decrypt/Verify writes to disk immediately

### ISSUE THREAD

**Issue by monolifed** [open-keychain/open-keychain#2146]
As far as I can tell, Decrypt/Verify writes to cache immediately after the user enters the password.

## Expected Behavior
Show verification status, ask user if they want it to be written to disk or decrypt in memory.

## Current Behavior
Decrypts to disk immediately if the password is correct.

## Context
The user might only want to verify the files without writing them to disk. Then decrypt them in a more secure environment.

## Your Environment

* OpenKeychain Version: 4.5 from F-Droid

**Comment by Valodim** [comment]
This is correct. However, the data is written into our internal storage only, so other apps can never access this data. While it's still desirable to keep this in memory only, in practice there is no good way around writing it down to disk if we want to pass the content to another app, so the only scenario where this matters is if the user doesn't actually want to look at the content of the decrypted data at all.

We might try to improve this implementation detail in the future, iirc Signal had some hacks to do in-memory files, but last I tried this did lead to compatibility problems. But it's not very high on our list of priorities.

**Comment by eighthave** [comment]
I'm starting to work on this problem right now, based on this thread:
https://lists.riseup.net/www/arc/openkeychain/2017-05/msg00013.html

Verifying without writing to disk should be easier, since OpenKeychain is receiving the encrypted file.  So it would just need to keep it in memory to verify.  Usually, verifying and decrypting are done at the same time though.  It seems like it could easily complicate the UX to add support for only verifying an encrypted file.  @monolifed can you provide more of a use case or user story to help us understand the context?

**Comment by monolifed** [comment]
I'd prefer them to be separate options if possible. For example:
If I choose verify, I would expect it to verify the file only without writing the decrypted file to somewhere on the disk.
If I choose decrypt and give a disk location, it should decrypt it only into that location on the disk.

If verifying without writing to disk is not possible, it would be good to inform the user that the operation is unsafe.

**Comment by Valodim** [comment]
If you think it's unsafe, please be more specific about an attack scenario where this could be harmful. I would argue that the operation is not unsafe - and if we thought it was, we would notify the user or do this differently.

**Comment by monolifed** [comment]
Let's not say unsafe but writing the decrypted and encrypted files to the same medium is always a security risk.
