### ISSUE TITLE
USB Security Token + PIN has UX issues

### ISSUE THREAD

**Issue by colltoaction** [open-keychain/open-keychain#2159]
I'm trying to use a Yubikey through USB-C OTG for GPG. I'm able to use it, but the UX is broken.

## Expected Behavior

1. app asks for my key to be inserted
1. once inserted, it asks for my PIN
1. keyboard shows up correctly

## Current Behavior

1. I open [Password Store (beta)](https://play.google.com/store/apps/details?id=com.zeapo.pwdstore)
1. I look for my encrypted file
1. It asks for my PIN before I even connect the key
1. If the key is connected, the keyboard sometimes doesn't show up

## Possible Solution

1. type PIN before inserting the key
1. dismiss dialogs when they show up repeatedly

## Your Environment

* Android Version: Android O
* OpenKeychain Version: 4.6 (4600)
* From Google Play or F-Droid?: Google Play
 
Thanks!

**Comment by dschuermann** [comment]
Our UX is currently optimized for NFC token. That's why we let the user enter the PIN before holding the token against the back of the device. Holding and at the same time typing is problematic with NFC.

Thanks for your feedback on USB usability. We should change that. What do you mean with "dismissing dialogs"? Do you mean the keyboard?

**Comment by tinchou** [comment]
I'm realizing one of the problems now: if you first connect the key, it'll appear as a physical keyboard to the system. Then, you are unable to type your PIN because the virtual keyboard doesn't show up.

What I mean by "dismissing dialogs": the PIN entry dialog sometimes shows up repeatedly.
