### ISSUE TITLE
OpenKeyChain is trying to obtain your current location

### ISSUE THREAD

**Issue by raven9nine** [open-keychain/open-keychain#2267]
Click on create new keys
Warning from phone:
OpenKeyChain is trying to obtain your current location
Allow/Deny

In contacts list: Check sync with OpenKeyChain.
Warnings from phone repeated several times:
OpenKeyChain is trying to obtain your current location.
Allow/Deny
OpenKeyChain is trying to access the camera.
Allow/Deny

Delete or Revoke Key
Warning from phone repeated several times:
OpenKeyChain is trying to obtain your current location.
Allow/Deny
OpenKeyChain is trying to access the camera.
Allow/Deny.

Alcatel A460G
Android 4.4.2
OpenKeyChain 4.8.1
F-Droid

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Android Version: 
* Device Model: 
* OpenKeychain Version: 
* From Google Play or F-Droid?:

**Comment by Valodim** [comment]
OpenKeychain can not request the location permission, you can check this in the [manifest](https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/AndroidManifest.xml#L63) file. We do use the camera permission, but only for QR code scanning.

I don't know what android system you have, but runtime permissions weren't in stock android in 4.4.2 (it was [introduced in android 6](https://developer.android.com/training/permissions/requesting.html)), so this is likely a vendor-specific mechanism and they messed something up. I suspect it mixes up the location and/or camera permission with the "contacts" permission, because we use that one in the dialogs you mentioned to suggest email addresses (key creation), and link keys to contacts (other two).

Either way, works as intended.

**Comment by raven9nine** [comment]
Thankyou for writing me regarding this matter there was a permissions app in 4.4.2 but it might be CPU specific.It is not the same as the one in Android 6 I believe is called app ops?
The one on my device is called, Permission Control v4.4.2-v4ADU-0Process: com.mediatek.security(mediatek is the cpu manufacturer)
I dont believe it is mixing up permissions, this is something else
The warning is triggered by clicking on the "Create My Key" button. The other 3 options on that screen do not trigger it.So the question is, what is it about the functionality of that button that is triggering this permission manager warning? It doesnt seem likely to be contacts because contacts have nothing to do with creating a key
--
Securely sent with Tutanota. Claim your encrypted mailbox today!
https://tutanota.com

12. Feb 2018 11:20 by notifications@github.com:

**Comment by raven9nine** [comment]
Further to my other reply, I have attached a screenshot.

--
Securely sent with Tutanota. Claim your encrypted mailbox today!
https://tutanota.com

12. Feb 2018 11:20 by notifications@github.com:

**Comment by Valodim** [comment]
Sorry, screenshots via mail do not work. I believe you that this dialog comes up, but it's a problem with your OS and not with OpenKeychain. We do not request location permission, ever.

> It doesnt seem likely to be contacts because contacts have nothing to do with creating a key

As I mentioned above, we use the contacts permission during key creation for completion of email addresses, and also during the other scenario you mentioned. No other permission is used during those times, so it's very likely that this is triggering it.

Note that Android 4.4.2 is *very* old and insecure, apps requesting weird permissions should be the least of your security concerns.

**Comment by raven9nine** [comment]
In the latest release, 4.9.1 (49100) fdroid build, this issue appears to be fixed, my device is no longer warning about location access, can someone explain the fix?

**Comment by dschuermann** [comment]
As we said:OpenKeychain can not request the location permission, you can check this in the manifest file.
