### ISSUE TITLE
Is there any way to choose a subkey for encrypt?

### ISSUE THREAD

**Issue by cpdyj** [open-keychain/open-keychain#2281]
Can I choose a subkey for encrypt?
## Expected Behavior

The beginning I need a strong encryption so I generated a RSA4096 key. But sometimes I need a short message. So is there any way to choose another subkey for encrypt?
## Possible Solution

Such as show a dialog or list?
## Your Environment

Thank you.

**Comment by 5h4d0ww0lf** [comment]
No, you cant because all your subkeys are connected to your public key and you encrypt with the public key of a receiver.

**Comment by cpdyj** [comment]
@5h4d0ww0lf  I means I have generated more than one RSA subkey (All of them enabled encrypt & verify). Which subkey will be used to encrypt data? Thanks.

**Comment by cpdyj** [comment]
@5h4d0ww0lf I means I have generated more than one RSA subkey (All of them enabled encrypt & verify). Which subkey will be used to encrypt data? Thanks.

**Comment by 5h4d0ww0lf** [comment]
@cpdyj, when you create your cert you generate a master keyset, Public key and secret key, subkeys, are in secret key and to encrypt you use a public key which is only one to each cert.

**Comment by cpdyj** [comment]
Thank you very much. I will go to wiki.

**Comment by 5h4d0ww0lf** [comment]
Sorry I have maybe confused you I meant that receiver has to have multiple subkeys

**Comment by dschuermann** [comment]
I think you both are confusing some details regarding subkeys. By default we generate the following OpenPGP configuration: https://github.com/open-keychain/open-keychain/wiki/OpenPGP-Security#key-creation-defaults

Since v 3.4 we encrypt to all subkeys with the capability flag for encryption: https://github.com/open-keychain/open-keychain/commit/7648602fc876df3ec5827f3bba1ebbb8ae92eaae
