### ISSUE TITLE
Any plan to support Brainpool curves?

### ISSUE THREAD

**Issue by alphazo** [open-keychain/open-keychain#2292]
I'm playing around with the OpenPGP card 3.3 JavaCard applet https://github.com/ANSSI-FR/SmartPGP running on a JavaCard that also has hardware support for Brainpool curves.
I have noticed that only RSA and NIST ECC are supported at the moment by Openkeychain. Is there any plan to support Brainpool curves as well?

**Comment by Valodim** [comment]
We do have support for Brainpool curves, as well as curve 25519, just not for generation. Have you tried what happens when you just use such a token?

I suspect it'll work fine up to [here](https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/operations/PsoDecryptTokenOp.java#L196), which only handles 25519 and NIST. Supporting brainpool might be as simple as looking for the right X9ECParams object there.

**Comment by alphazo** [comment]
You are right. I can import my Brainpool pub key and then connect the OpenPGP card that has the corresponding private key material. The import goes just fine and key shows as valid. Now if I try to decrypt a simple text file, I get prompted for the PIN and see the communication going on with the card but no decrypted message is displayed. A blank screen shows up for a second but then it goes back to the OpenKeychain Encrypt/Decrypt GUI. Going over the same process with a RSA key shows the decrypted message.

**Comment by Valodim** [comment]
Cool. It's possible this might just work with the simple patch in #2293.

I prepared a debug version of openkeychain from that master branch, if you want you can give it a shot: [openkeychain-debug-brainpool.apk.zip](https://github.com/open-keychain/open-keychain/files/1799361/openkeychain-debug-brainpool.apk.zip) This will install separately from regular openkeychain (with a blue icon). Of course you can also compile it yourself, if you're more comfortable with that.

**Comment by alphazo** [comment]
Thanks a lot. The proposed debug version actually works with my Brainpool P512 key located on an OpenPGP 3.3 card (Javacard Applet) using an Omnikey Cardman 3121 reader and a USB type-A to type-C converter on a Huawei Mate 10 Pro (not rooted) phone.

**Comment by Valodim** [comment]
Great, thanks for testing! The fix will be included in the next release :+1:
