### ISSUE TITLE
Decryption not possible "No encrypted data of a known private key was found in the data stream".

### ISSUE THREAD

**Issue by viper-666** [open-keychain/open-keychain#2427]
Since my key was very old and weak I created a new key RSA 3072 bit with GNUPG.

Since then I can't decrypt new mails encrypted with this key with OpenKeychain anymore.
But I can decrypt the same mails with Enigmail and my new key.

I have the German version of OpenKeychain so the error messages are translated to English and may be different:

The protocol says:

German:
Es wird versucht OpenPGP-daten zu verarbeiten
Starte Entschlüsselungsvorgang...
Block asymetrisch verschlüsselter Daten für Schlüssel 0x7a5c9dc97c4ef59b gefunden
Schlüssel ist kein gültiger Verschlüsselung-Schlüssel, überspringe...
Es wurden keine verschlüsselten Daten eines bekannten privaten Schlüssels im Datenstrom gefunden!

English:

An attempt is made to process OpenPGP data.

Starting decryption process...

Block of asymmetrically encrypted data found for key 0x7a5c9dc97c4ef59b

Key is not a valid encryption key, skip...

No encrypted data of a known private key was found in the data stream!

## Your Environment

* Android Version: 
8.0.0
* Device Model: 
OnePlus 3
* OpenKeychain Version: 
5.1
* From Google Play or F-Droid?: 
Google Play

**Comment by sicherist** [comment]
Did you find a solution or workaround? I have encountered the same problem but only with messages from my bank. When I receive an encrypted message that was sent from Thunderbird/Enigmail the messages are decrypted fine.

Inspired by #2215 I have a theory what might be the problem: My PGP-Key consists of a primary key and a subkey. They have different Key IDs. Only the subkey is supposed to be used for encryption. I think the problem might be that the bank uses the primary key to encrypt and Openkeychain refuses to decrypt, because the key is not supposed to be used for encryption. Enigmail doesn't seem to care and decrypt it anyway. When the e-mails from the bank fail to decrypt the log looks just like yours:

> 
> [DEBUG] Starte Entschlüsselungsvorgang...
>   [DEBUG] Block asymmetrisch verschlüsselter Daten für Schlüssel 0xYYYYYYYYYY gefunden
>    [DEBUG] Schlüssel ist kein gültiger Verschlüsselung-Schlüssel, überspringe...
>    [ERROR] Es wurden keine verschlüsselten Daten eines bekannten privaten Schlüssels im Datenstrom gefunden!

0xYYYYYYYYYY is the primary key

When I decrypt a message that was encrypted in Enigmail the log begins like this:

> [DEBUG] Starte Entschlüsselungsvorgang...
>   [DEBUG] Block asymmetrisch verschlüsselter Daten für Schlüssel 0xZZZZZZZZ gefunden

... and continues to decrypt fine. 0xZZZZZZZZ is the ID of the subkey.

**Comment by sicherist** [comment]
#2413

**Comment by viper-666** [comment]
Yes I am too customer of the 1822direkt bank so it is the Issue [https://github.com/open-keychain/open-keychain/issues/2413](url)
