### ISSUE TITLE
1Password autofill not working

### ISSUE THREAD

**Issue by sweepies** [open-keychain/open-keychain#2449]
## Expected Behavior

I have a login in 1Password containing nothing but my PGP passphrase in the password field. I expect it to fill when I select that note.

## Current Behavior

Nothing happens.
## Steps to Reproduce (for bugs)

1. Select key
2. Select `Backup key`
3. Select `Autofill with 1Password`
4. Select login containing password

## Context

In order to input my password, I must first open 1Password and copy it to clipboard.

## Your Environment

* Android Version: **9**
* Device Model: **SM-G965W (Samsung Galaxy S9 Plus)**
* OpenKeychain Version:  **5.2 (52009)**
* From Google Play or F-Droid?: **Google Play**

**Comment by JamesDean829** [comment]
I habe a similiar problem. If I try to send an E-Mail via k9, openkeychain asks for my password.

They password is in my other app KeePass. Normally I just copy it from KeePass and paste it into the field from OpenKeyChain. But: Sometimes it happens that there is no option for "paste", there is just the option " autofill" and no other options, so that I cannot paste my password. If I click the Autofill option, there appears a small popup below of KeePass, it also opens if I click on it. If I select the corresponding account (In KeePass I made an entry for Openkeychain) it returns back to the entry field of openkeychain but it does not transfer the passwort from KeePass, the field is still empty.

So I always have to do it manually because the autofill never works. And even if I do it manually, sometimes the paste function is missing, so I cannot send a mail anymore (at least not encrypted). Sometimes if I close and reopen the password field of Openkeychain around ten times, suddenly the paste option appears again.

I have no idea how to reproduce the issue. But it happens on my OnePlus 2 and independently on my Tab S6 Lite as well! I use Lineage 17.1. but it already happened when I had the old OS Lineage 16.

This is quite a pain, because this bug happens around with every second mail I am sending. If I type in the password corrcetly I usually save it "until manually reset", but its quite often deleted, because I reboot the quite often.

It would be really cool to save the password for infinity, I know its not save or recommended but this would reduce the work of people facing this issue tremendously. I guess if you make a warning there, this would be a good option (that the password is saved even a reboot).

**Comment by josebama** [comment]
I have the same issue. When selecting the password from the autofill list the dialog disappears for a moment and then reappears again, empty.

**Comment by wildcard27** [comment]
This is super annoying. Same deal with Password Store. Is there anything planned for fixing this? I'd be happy to look into it myself but, like @josebama , my Java/Kotlin isn't up to scratch
