### ISSUE TITLE
OpenKeychain does not support 1024-bit DSA keys

### ISSUE THREAD

**Issue by marianoju** [open-keychain/open-keychain#2610]
## Current Behavior

1024-bit DSA public keys can be imported but are greyed out in the overview (key listing) and can not be used for encryption. 
The user is warned, that 1024-bit DSA keys are considered unsecure. 

> This key uses the DSA algorithm with a strength of 1024 bits. A secure key should have a strength of 2048 bits. 
> This key can\'t be upgraded. For secure communication, the owner must generate a new key.

This warning is not actionable. In the situation where the 1024-bit DSA key is some else's there is nothing the user can do to fix the situation but 
a) forgo encryption thoroughly, or 
b) use another software, that does (still) support 1024-bit DSA keys. 

## Expected Behavior

User should be presented with an option to use these keys for encryption. 

## Rationale 
I understand that and why 1024-bit DSA keys can be and are considered unsecure. 
Nonetheless user can generally not force the owner of the key to generate a new, stronger key. 
Encryption with 1024-bit DSA keys should be considered _more_ secure than no encryption at all. 

## Possible Solution

Provide an option to manually override the warning (“I understand the risks associated with using a weak key.”) 

## Steps to Reproduce (for bugs)

1. Import an 1024-bit DSA key. 
2. Take a look at the keys listed. 
3. Take a look at the details of the 1024-bit DSA key. 
4. Attempt to encrypt with the 1024-bit DSA key. 

## Context

I am communicating by email with someone using an 1024-bit DSA key generated 2007. This key does not expire. 

## Your Environment

* Android Version: 10 
* Device Model: FP3 
* OpenKeychain Version: 5.5 
* From Google Play or F-Droid?: F-Droid

**Comment by dkg** [comment]
I understand the rationale for the user wanting to do this in one isolated instance.

however, there is an ecosystem to consider here.  What happens when you send an encrypted e-mail to multiple people, one of whom is using a 1024-bit DSA or RSA key?  if someone wants to "reply all" (in an encrypted message) now they are obliged to make the same decision, right?

The better thing to do is to encourage the person with the weak key to replace their key.

(pedantry postscriptum: the actual encryption likely targets your peer's encryption-capable subkey, which could be either el gamal or RSA -- not DSA, which is for signatures-only; But even if this subkey is strong, the argument we're having here still holds.  That's because we're talking about whether to accept your peer's certificate itself, which is anchored in a weak primary key.  An attacker who is able to take control of the primary key's secret key material could add a new subkey -- one that they control -- to the certificate)

**Comment by Valodim** [comment]
1024D keys are insecure, and should have been more aggressively deprecated, by more implementations, more than a decade ago. OpenKeychain won't support those keys.
