### ISSUE TITLE
API: publish aar library on maven?

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#293]

**Comment by ashh87** [comment]
Can Maven aars be signed? This would be great for Maven open source projects, which could reference a known good API, rather than asking the project to trust a self-built aar, which is the only way I can see of getting it to work, unless you can convince maven to build a gradle project...

If there's a better way, please let me know!

**Comment by dschuermann** [comment]
I started working on it: https://github.com/open-keychain/openpgp-api-lib/commit/ab17ae851218cfb5e98ab69dc7e55cd30b14faa3

Unfortunatly, the lib currently does not build alone. Needs investigation. Looks like problems with aidl.

**Comment by dschuermann** [comment]
Both libs are now on jcenter.
See https://github.com/open-keychain/openpgp-api
and https://github.com/open-keychain/openkeychain-intents

**Comment by Valodim** [comment]
:tada:
