### ISSUE TITLE
Lock pattern passphrases

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#972]
Related to #740.

We have been throwing around the idea of lock pattern passphrases for a while now. The major problem we'd be facing is exported keys, lock patterns have low entropy (compared to passphrases) so an attacker who can get a hold of the secret key (#194 related) could easily brute-force the passphrase.

A neat solution to sidestep these problems would be introducing a local custom packet which encrypts the passphrase (or even the private key itself) with the lock pattern. As long as our export logic takes care never to export this packet, that would enable OpenKeychain to access the private key using the lock pattern, but an exported key would still be protected by the regular passphrase just like before.

This is not trivial to implement, but most connecting pieces to the puzzle are already there: Passphrase type flags in the database, passphrase changing happens in a single place, the only part missing would be a definite place of "prepare key for export", but even that should be relatively simple since ImportExportOperation is already nicely encapsulated.

This is not an important feature or anything, and it's not even decided if we want it. Leaving this here for discussion.

**Comment by Valodim** [comment]
I started working on this by allowing addition of "notation data" to keyrings in non-exportable direct key signature packets (in 576e6fd0cca41691a52db8e1325508f00a6e9bc6, primarily) and adding a "pin" type of passphrase. dominik started working on the lock pattern gui part.

todos from the top of my head:
- [ ] make sure non-exportable packets actually aren't exported
- [ ] [change passphrase](https://github.com/open-keychain/open-keychain/issues/194) on key export
- [ ] rework 'change passphrase' dialog (maybe move from 'edit key' into its own activity?)

**Comment by dschuermann** [comment]
Much more work is required on the GUI part. I just switched to a different lib: https://github.com/open-keychain/open-keychain/commit/7bddd5be1d76360f1112e780091ee6636591caae

**Comment by ashh87** [comment]
It would be interesting to have the lockpattern not encrypt a passphrase, but part of one. Passphrase alternatives (and the passphrase itself) could be abstracted out so that they unlock one or several parts of a Shamir secret sharing-split passphrase. In the simplest user case, a passphrase would unlock all necessary parts of the real passphrase (a high entropy random string), allowing it to be the sole method of key unlock. A lock pattern could do the same thing - which would address this issue.

More advanced users (or anybody suitably guided) might then like to extend the idea of multi-factor authentication - something you own, something you know, etc. For example, an unlock pattern could unlock one part of a Shamir secret, with a wearable device providing the rest. If, for example, the wearable were not present, there wouldn't be enough of the secret to be able to use the key, and a fallback method could be used. This could simply be a (high entropy) passphrase which was given the necessary number of Shamir parts to unlock the true passphrase on its own.

By having unlock methods inherit from a class which can be passed a number of Shamir secrets, different methods can be easily added later. Unlock methods would then be free to deal with the parts they are trusted with on their own - a lockpattern unlocker would have to encrypt its secrets using the pattern, a smartwatch app might simply store the secrets and make the user confirm that they wish to use them when they try to unlock their key. OKC would then only need minimal knowledge of each method, encapsulated in a class, and past that, the process of unlocking the key passphrase only depends on being passed enough Shamir secrets from whatever can be provided. The only extra knowledge (I can think of right now) that could be useful is the type of unlock method - if an unlocker marked as 'what you have'  is unavailable, then other methods intended to be used with that one wouldn't be usable, and the app could detect this and move straight to the fallback method.

Of course, there's a lot of work to do to make this happen. Is it sensible, and if so, is it worth doing?

**Comment by Valodim** [comment]
this info is old at this point
